import { SkinId } from "../..";
import { Skin } from "./Skin";
import { TierEnum } from "src/InterFacesEnumsAndTypes/Tiers";
import { ItemCost } from "src/Entity/Item/Subclass/ItemCost";
import { createEquipmentCraftingAttributes } from "src/Entity/Item/Misc/Resource/EquipmentCraftingAttributes";

type SkinDefinition = {
  name: string;
  description: string;
  tier: TierEnum;
  weight: number;
  baseCost: number;
  craftingAttributes?: ReturnType<typeof createEquipmentCraftingAttributes>;
};

const SKIN_DATA: Record<SkinId, SkinDefinition> = {
  [SkinId.WolfPelt]: {
    name: "Wolf Pelt",
    description: "Coarse pelt stripped from wolves; common material for warm cloaks.",
    tier: TierEnum.common,
    weight: 6,
    baseCost: 90,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.DirewolfPelt]: {
    name: "Direwolf Pelt",
    description: "Thick hide from direwolves; naturally resistant to frost.",
    tier: TierEnum.uncommon,
    weight: 8,
    baseCost: 180,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { water: 1 } }),
  },
  [SkinId.BearHide]: {
    name: "Bear Hide",
    description: "Dense and heavy hide from bears; excellent for rugged armor.",
    tier: TierEnum.uncommon,
    weight: 14,
    baseCost: 210,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { blunt: 1 } }),
  },
  [SkinId.BoarHide]: {
    name: "Boar Hide",
    description: "Fibrous hide from boars; suited for sturdy leatherworking.",
    tier: TierEnum.common,
    weight: 12,
    baseCost: 120,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { pDef: 1 } }),
  },
  [SkinId.StagFur]: {
    name: "Stag Fur",
    description: "Soft decorative fur taken from proud stags.",
    tier: TierEnum.uncommon,
    weight: 5,
    baseCost: 160,
    craftingAttributes: createEquipmentCraftingAttributes({ tags: ["comfort"] }),
  },
  [SkinId.ElephantHide]: {
    name: "Elephant Hide",
    description: "Massive, wrinkled hide; prized for shield plating.",
    tier: TierEnum.rare,
    weight: 20,
    baseCost: 360,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { blunt: 1 } }),
  },
  [SkinId.CrocodileHide]: {
    name: "Crocodile Hide",
    description: "Scaled hide from river beasts; difficult to pierce.",
    tier: TierEnum.uncommon,
    weight: 16,
    baseCost: 220,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { pierce: 1 } }),
  },
  [SkinId.TigerPelt]: {
    name: "Tiger Pelt",
    description: "Vibrant striped pelt; ceremonial and deadly.",
    tier: TierEnum.rare,
    weight: 7,
    baseCost: 320,
    craftingAttributes: createEquipmentCraftingAttributes({ attributes: { dexterity: 1 } }),
  },
  [SkinId.LionMane]: {
    name: "Lion Mane",
    description: "Luxurious mane from a lion; valued by nobles.",
    tier: TierEnum.rare,
    weight: 6,
    baseCost: 340,
    craftingAttributes: createEquipmentCraftingAttributes({ attributes: { charisma: 1 } }),
  },
  [SkinId.DeerHide]: {
    name: "Deer Hide",
    description: "Soft, supple hide ideal for light armor.",
    tier: TierEnum.common,
    weight: 6,
    baseCost: 110,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { pDef: 1 } }),
  },
  [SkinId.GoatHide]: {
    name: "Goat Hide",
    description: "Coarse hide from mountain goats; rugged everyday leather.",
    tier: TierEnum.common,
    weight: 7,
    baseCost: 100,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { pDef: 1 } }),
  },
  [SkinId.BisonHide]: {
    name: "Bison Hide",
    description: "Heavy hide from plains bison; thick and durable.",
    tier: TierEnum.uncommon,
    weight: 18,
    baseCost: 230,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { pDef: 1 } }),
  },
  [SkinId.DragonlingScale]: {
    name: "Dragonling Scales",
    description: "Small draconic scales that hum with latent heat.",
    tier: TierEnum.rare,
    weight: 6,
    baseCost: 480,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.WyvernScale]: {
    name: "Wyvern Scales",
    description: "Flexible flight scales retaining a faint charge.",
    tier: TierEnum.rare,
    weight: 8,
    baseCost: 620,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.DrakeScale]: {
    name: "Drake Scales",
    description: "Large reinforced scales from land drakes.",
    tier: TierEnum.epic,
    weight: 10,
    baseCost: 900,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.WyrmScale]: {
    name: "Wyrm Scales",
    description: "Massive scales from deep wyrms; nearly impenetrable.",
    tier: TierEnum.legendary,
    weight: 12,
    baseCost: 160000,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.SeaWyrmScale]: {
    name: "Sea Wyrm Scales",
    description: "Salt-resistant scales that shimmer with azure light.",
    tier: TierEnum.epic,
    weight: 11,
    baseCost: 980,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.DragonScale]: {
    name: "Dragon Scale",
    description: "Apex draconic scale resonating with elemental power.",
    tier: TierEnum.legendary,
    weight: 14,
    baseCost: 210000,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.LizardSkin]: {
    name: "Lizard Skin",
    description: "Small flexible scales; favored in light armor.",
    tier: TierEnum.common,
    weight: 4,
    baseCost: 90,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.TurtleShell]: {
    name: "Turtle Shell Plates",
    description: "Hardened shell fragments used for shields.",
    tier: TierEnum.uncommon,
    weight: 18,
    baseCost: 260,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.SharkSkin]: {
    name: "Shark Skin",
    description: "Rough skin from a shark; abrasive and durable.",
    tier: TierEnum.uncommon,
    weight: 8,
    baseCost: 210,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.WhaleSkin]: {
    name: "Whale Skin",
    description: "Thick oily hide; naturally water-resistant.",
    tier: TierEnum.rare,
    weight: 24,
    baseCost: 420,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.Chitin]: {
    name: "Chitin Plates",
    description: "Segmented exoskeleton from large insects.",
    tier: TierEnum.common,
    weight: 5,
    baseCost: 120,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.SerpentSkin]: {
    name: "Serpent Skin",
    description: "Supple scaled hide; imbues agility when crafted.",
    tier: TierEnum.uncommon,
    weight: 4,
    baseCost: 170,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.FiendHide]: {
    name: "Fiend Hide",
    description: "Planar-tainted hide faintly warm to the touch.",
    tier: TierEnum.epic,
    weight: 9,
    baseCost: 950,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { fire: 1 }, planarAttunement: 1 }),
  },
  [SkinId.AetherSkin]: {
    name: "Aether Skin",
    description: "Translucent hide from magical beasts; shimmers in moonlight.",
    tier: TierEnum.epic,
    weight: 7,
    baseCost: 880,
    craftingAttributes: createEquipmentCraftingAttributes({ planarAttunement: 1 }),
  },
  [SkinId.SpiritHide]: {
    name: "Spirit Hide",
    description: "Ethereal hide from phantasmal beasts; featherlight.",
    tier: TierEnum.rare,
    weight: 3,
    baseCost: 540,
    craftingAttributes: createEquipmentCraftingAttributes({ elements: { order: 1 } }),
  },
  [SkinId.CrystalCarapace]: {
    name: "Crystal Carapace",
    description: "Gemlike plates from crystal-shelled creatures.",
    tier: TierEnum.epic,
    weight: 10,
    baseCost: 1100,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.GriffonFeatheredHide]: {
    name: "Griffon Feathered Hide",
    description: "Durable hide flecked with feathers from a griffon.",
    tier: TierEnum.rare,
    weight: 9,
    baseCost: 620,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.BasiliskScale]: {
    name: "Basilisk Scale",
    description: "Petrifying scale; dangerous to handle unaided.",
    tier: TierEnum.epic,
    weight: 9,
    baseCost: 1200,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.ChimeraHide]: {
    name: "Chimera Hide",
    description: "Chaotic hide stitched by nature; radiates volatile energy.",
    tier: TierEnum.epic,
    weight: 12,
    baseCost: 1050,
    craftingAttributes: createEquipmentCraftingAttributes(),
  },
  [SkinId.HydraSkin]: {
    name: "Hydra Skin",
    description: "Regenerative scaled hide harvested from a hydra.",
    tier: TierEnum.legendary,
    weight: 13,
    baseCost: 170000,
    craftingAttributes: createEquipmentCraftingAttributes({ elements: { water: 1 }, tags: ["regen-potential"] }),
  },
  [SkinId.YetiFur]: {
    name: "Yeti Fur",
    description: "Exceptionally thick fur vital for survival in extreme cold.",
    tier: TierEnum.rare,
    weight: 10,
    baseCost: 480,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { water: 1 } }),
  },
  [SkinId.SalamanderSkin]: {
    name: "Salamander Skin",
    description: "Heat-resistant hide; remains cool even in flame.",
    tier: TierEnum.rare,
    weight: 7,
    baseCost: 560,
    craftingAttributes: createEquipmentCraftingAttributes({ defense: { fire: 1 } }),
  },
  [SkinId.PhoenixFeatheredHide]: {
    name: "Phoenix Feathered Hide",
    description: "Fiery feathers fused to hide; pulses with embers.",
    tier: TierEnum.legendary,
    weight: 6,
    baseCost: 190000,
    craftingAttributes: createEquipmentCraftingAttributes({ elements: { fire: 2 }, planarAttunement: 1, tags: ["resonates:fire"] }),
  },
  [SkinId.ManticoreHide]: {
    name: "Manticore Hide",
    description: "Spiked hide laced with venom; prized by daring artisans.",
    tier: TierEnum.epic,
    weight: 11,
    baseCost: 980,
    craftingAttributes: createEquipmentCraftingAttributes({ tags: ["venomous"] }),
  },
  [SkinId.LeviathanScale]: {
    name: "Leviathan Scale",
    description: "Colossal oceanic scale; nearly indestructible.",
    tier: TierEnum.legendary,
    weight: 18,
    baseCost: 220000,
    craftingAttributes: createEquipmentCraftingAttributes({ elements: { water: 2 }, tags: ["resonates:water"] }),
  },
};

export const skinItems: Record<SkinId, Skin> = Object.fromEntries(
  Object.entries(SKIN_DATA).map(([id, data]) => [
    id,
    new Skin({
      id: id as SkinId,
      name: { en: data.name, th: "" },
      description: { en: data.description, th: "" },
      tier: data.tier,
      weight: data.weight,
      cost: new ItemCost({ baseCost: data.baseCost }),
      isCraftable: false,
      image: id + ".png",
      equipmentCraftingAttributes: data.craftingAttributes ?? createEquipmentCraftingAttributes(),
    }),
  ]),
) as Record<SkinId, Skin>;
