import {
  BodyId,
  EarId,
  FootId,
  HandId,
  HeadWearId,
  LegId,
  NeckId,
  RingId,
  UtilId,
  WeaponId,
  AxeId,
  BladeId,
  BookWId,
  BowId,
  DaggerId,
  HammerId,
  OrbId,
  ShieldId,
  SpearId,
  StaffId,
  SwordId,
  WandId,
} from "src/Entity/Item";
import {
  SkillId,
  BarbarianSkillId,
  ClericSkillId,
  DruidSkillId,
  DuelistSkillId,
  GuardianSkillId,
  InquisitorSkillId,
  KnightSkillId,
  MageSkillId,
  MonkSkillId,
  MysticSkillId,
  PaladinSkillId,
  RogueSkillId,
  ScholarSkillId,
  ShamanSkillId,
  SpellBladeSkillId,
  WarriorSkillId,
  WarlockSkillId,
  WitchSkillId,
} from "src/Entity/Skill/enums";
import {
  CharacterEquipmentSlot,
  ClassEnum,
  ProficiencyKey,
} from "src/InterFacesEnumsAndTypes/Enums";

type Bonus = {
  proficiencies: ProficiencyBonus;
  startingSkills: StartingSkills;
  startingEquipments: StartingEquipments;
};

type ProficiencyBonus = { key: ProficiencyKey; value: number }[];
type StartingSkills = SkillId[];
type StartingEquipments = {
  [CharacterEquipmentSlot.headWear]: HeadWearId | null;
  [CharacterEquipmentSlot.body]: BodyId | null;
  [CharacterEquipmentSlot.leg]: LegId | null;
  [CharacterEquipmentSlot.hand]: HandId | null;
  [CharacterEquipmentSlot.foot]: FootId | null;
  [CharacterEquipmentSlot.util]: UtilId | null;
  [CharacterEquipmentSlot.ringL]: RingId | null;
  [CharacterEquipmentSlot.ringR]: RingId | null;
  [CharacterEquipmentSlot.earL]: EarId | null;
  [CharacterEquipmentSlot.earR]: EarId | null;
  [CharacterEquipmentSlot.neck]: NeckId | null;
  [CharacterEquipmentSlot.rightHand]: WeaponId | null;
  [CharacterEquipmentSlot.leftHand]: WeaponId | null;
};

const classBonus: Record<ClassEnum, Bonus> = {
  [ClassEnum.Cleric]: {
    proficiencies: [
      { key: "book", value: +3 },
      { key: "hammer", value: +2 },
      { key: "shield", value: +1 },
    ],
    startingSkills: [
      ClericSkillId.Heal as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.Robe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: StaffId.QuarterStaff,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Seer]: {
    proficiencies: [
      { key: "orb", value: +3 },
      { key: "dagger", value: +2 },
      { key: "book", value: +1 },
    ],
    startingSkills: [],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: OrbId.Orb,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Mage]: {
    proficiencies: [
      { key: "wand", value: +3 },
      { key: "staff", value: +2 },
      { key: "book", value: +1 },
    ],
    startingSkills: [
      MageSkillId.ArcaneBolt as SkillId,
      MageSkillId.FireBolt as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: WandId.Wand,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Mystic]: {
    proficiencies: [
      { key: "orb", value: +3 },
      { key: "bareHand", value: +2 },
      { key: "wand", value: +1 },
    ],
    startingSkills: [
      MysticSkillId.MistStep as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: OrbId.Orb,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Rogue]: {
    proficiencies: [
      { key: "dagger", value: +3 },
      { key: "bow", value: +2 },
      { key: "blade", value: +1 },
    ],
    startingSkills: [
      RogueSkillId.ThrowingKnives as SkillId,
      RogueSkillId.RetreatDash as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: DaggerId.Knife,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.SpellBlade]: {
    proficiencies: [
      { key: "sword", value: +3 },
      { key: "blade", value: +2 },
      { key: "wand", value: +1 },
    ],
    startingSkills: [
      SpellBladeSkillId.PlanarEdge as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: SwordId.ShortSword,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Shaman]: {
    proficiencies: [
      { key: "staff", value: +3 },
      { key: "spear", value: +2 },
      { key: "axe", value: +1 },
    ],
    startingSkills: [
      ShamanSkillId.HexOfRot as SkillId,
      ShamanSkillId.HolyRattle as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.Robe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: StaffId.QuarterStaff,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Barbarian]: {
    proficiencies: [
      { key: "axe", value: +3 },
      { key: "hammer", value: +2 },
      { key: "bareHand", value: +1 },
    ],
    startingSkills: [
      BarbarianSkillId.Rage as SkillId,
      BarbarianSkillId.RecklessSwing as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: AxeId.Axe,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Warrior]: {
    proficiencies: [
      { key: "blade", value: +3 },
      { key: "sword", value: +2 },
      { key: "spear", value: +1 },
    ],
    startingSkills: [
      WarriorSkillId.PowerStrike as SkillId,
      WarriorSkillId.Cleave as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.PaddedArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: BladeId.Scimitar,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Knight]: {
    proficiencies: [
      { key: "spear", value: +3 },
      { key: "shield", value: +2 },
      { key: "sword", value: +1 },
    ],
    startingSkills: [
      KnightSkillId.PrecisionThrust as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.ChainShirt,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: SpearId.Dory,
      [CharacterEquipmentSlot.leftHand]: ShieldId.Buckler,
    },
  },
  [ClassEnum.Guardian]: {
    proficiencies: [
      { key: "shield", value: +3 },
      { key: "hammer", value: +2 },
      { key: "axe", value: +1 },
    ],
    startingSkills: [
      GuardianSkillId.ShieldUp as SkillId,
      GuardianSkillId.Bash as SkillId,
      GuardianSkillId.Taunt as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.ChainShirt,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: HammerId.Hammer,
      [CharacterEquipmentSlot.leftHand]: ShieldId.Buckler,
    },
  },
  [ClassEnum.Paladin]: {
    proficiencies: [
      { key: "hammer", value: +3 },
      { key: "shield", value: +2 },
      { key: "sword", value: +1 },
    ],
    startingSkills: [
      PaladinSkillId.DivineStrike as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.StuddedLeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: HammerId.Hammer,
      [CharacterEquipmentSlot.leftHand]: ShieldId.Buckler,
    },
  },
  [ClassEnum.Druid]: {
    proficiencies: [
      { key: "staff", value: +3 },
      { key: "spear", value: +2 },
      { key: "bow", value: +1 },
    ],
    startingSkills: [
      DruidSkillId.VineWhip as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.HideArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: StaffId.QuarterStaff,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Monk]: {
    proficiencies: [
      { key: "bareHand", value: +3 },
      { key: "staff", value: +2 },
      { key: "blade", value: +1 },
    ],
    startingSkills: [
      MonkSkillId.PalmStrike as SkillId,
      MonkSkillId.Meditation as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.Tunic,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: null,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Warlock]: {
    proficiencies: [
      { key: "orb", value: +3 },
      { key: "axe", value: +2 },
      { key: "bow", value: +1 },
    ],
    startingSkills: [
      WarlockSkillId.ChaosBolt as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: OrbId.Orb,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Duelist]: {
    proficiencies: [
      { key: "sword", value: +3 },
      { key: "shield", value: +2 },
      { key: "bow", value: +1 },
    ],
    startingSkills: [
      DuelistSkillId.PreciseStrike as SkillId,
      DuelistSkillId.BladeFlurry as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: SwordId.ShortSword,
      [CharacterEquipmentSlot.leftHand]: ShieldId.Buckler,
    },
  },
  [ClassEnum.Witch]: {
    proficiencies: [
      { key: "wand", value: +3 },
      { key: "book", value: +2 },
      { key: "dagger", value: +1 },
    ],
    startingSkills: [
      WitchSkillId.PoisonDart as SkillId,
      WitchSkillId.ChaosBinding as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: WandId.Wand,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Inquisitor]: {
    proficiencies: [
      { key: "book", value: +3 },
      { key: "bow", value: +2 },
      { key: "wand", value: +1 },
    ],
    startingSkills: [
      InquisitorSkillId.RadiantSmite as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: BookWId.Bible,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Scholar]: {
    proficiencies: [
      { key: "book", value: +3 },
      { key: "sword", value: +2 },
      { key: "dagger", value: +1 },
    ],
    startingSkills: [
      ScholarSkillId.DisruptPattern as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: BookWId.Codex,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Engineer]: {
    proficiencies: [
      { key: "bow", value: +3 },
      { key: "hammer", value: +2 },
      { key: "bareHand", value: +1 },
    ],
    startingSkills: [],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: BowId.ShortBow,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Nomad]: {
    proficiencies: [
      { key: "spear", value: +3 },
      { key: "dagger", value: +2 },
      { key: "hammer", value: +1 },
    ],
    startingSkills: [],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: SpearId.Dory,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
};

export { classBonus };
export type { Bonus, ProficiencyBonus, StartingSkills, StartingEquipments };
