import {
  BodyId,
  EarId,
  FootId,
  HandId,
  HeadWearId,
  LegId,
  NeckId,
  RingId,
  UtilId,
  WeaponId,
  AxeId,
  BladeId,
  BookWId,
  BowId,
  DaggerId,
  HammerId,
  OrbId,
  ShieldId,
  SpearId,
  StaffId,
  SwordId,
  WandId,
} from "src/Entity/Item";
import {
  SkillId,
  BarbarianSkillId,
  ClericSkillId,
  DruidSkillId,
  DuelistSkillId,
  GuardianSkillId,
  InquisitorSkillId,
  KnightSkillId,
  MageSkillId,
  MonkSkillId,
  MysticSkillId,
  PaladinSkillId,
  RogueSkillId,
  ScholarSkillId,
  ShamanSkillId,
  SpellBladeSkillId,
  WarriorSkillId,
  WarlockSkillId,
  WitchSkillId,
  SeerSkillId,
  NomadSkillId,
  EngineerSkillId,
} from "src/Entity/Skill/enums";
import {
  CharacterEquipmentSlot,
  ClassEnum,
} from "src/InterFacesEnumsAndTypes/Enums";
import { ClassBonus } from "./types";


const classBonus: Record<ClassEnum, ClassBonus> = {
  [ClassEnum.Cleric]: {
    proficiencies: {
      three: "book",
      two: "hammer",
      one: "shield",
    },
    startingSkills: [
      ClericSkillId.Radiance,
      ClericSkillId.Heal,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.Robe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: StaffId.QuarterStaff,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Seer]: {
    proficiencies: {
      three: "orb",
      two: "dagger",
      one: "book",
    },
    startingSkills: [
      SeerSkillId.ThreadSnip,
      SeerSkillId.PlanarEcho
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: OrbId.Orb,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Mage]: {
    proficiencies: {
      three: "wand",
      two: "staff",
      one: "book",
    },
    startingSkills: [
      MageSkillId.ArcaneShield,
      MageSkillId.ArcaneBolt,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: WandId.Wand,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Mystic]: {
    proficiencies: {
      three: "orb",
      two: "bareHand",
      one: "wand",
    },
    startingSkills: [
      MysticSkillId.InnerVeil,
      MysticSkillId.MistStep as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: OrbId.Orb,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Rogue]: {
    proficiencies: {
      three: "dagger",
      two: "bow",
      one: "blade",
    },
    startingSkills: [
      RogueSkillId.BleedingCut,
      RogueSkillId.ThrowingKnives
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: DaggerId.Knife,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.SpellBlade]: {
    proficiencies: {
      three: "sword",
      two: "blade",
      one: "wand",
    },
    startingSkills: [
      SpellBladeSkillId.WindSlash,
      SpellBladeSkillId.PlanarEdge,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: SwordId.ShortSword,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Shaman]: {
    proficiencies: {
      three: "staff",
      two: "spear",
      one: "axe",
    },
    startingSkills: [
      ShamanSkillId.HexOfRot,
      ShamanSkillId.MendSpirit,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.Robe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: StaffId.QuarterStaff,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Barbarian]: {
    proficiencies: {
      three: "axe",
      two: "hammer",
      one: "bareHand",
    },
    startingSkills: [
      BarbarianSkillId.RecklessSwing,
      BarbarianSkillId.Rage
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: AxeId.Axe,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Warrior]: {
    proficiencies: {
      three: "blade",
      two: "sword",
      one: "spear",
    },
    startingSkills: [
      WarriorSkillId.WarCry,
      WarriorSkillId.PowerStrike,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.PaddedArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: BladeId.Scimitar,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Knight]: {
    proficiencies: {
      three: "spear",
      two: "shield",
      one: "sword",
    },
    startingSkills: [
      KnightSkillId.PrecisionThrust,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.ChainShirt,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: SpearId.Dory,
      [CharacterEquipmentSlot.leftHand]: ShieldId.Buckler,
    },
  },
  [ClassEnum.Guardian]: {
    proficiencies: {
      three: "shield",
      two: "hammer",
      one: "axe",
    },
    startingSkills: [
      GuardianSkillId.ShieldUp as SkillId,
      GuardianSkillId.Taunt as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.ChainShirt,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: HammerId.Hammer,
      [CharacterEquipmentSlot.leftHand]: ShieldId.Buckler,
    },
  },
  [ClassEnum.Paladin]: {
    proficiencies: {
      three: "hammer",
      two: "shield",
      one: "sword",
    },
    startingSkills: [
      PaladinSkillId.DivineStrike,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.StuddedLeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: HammerId.Hammer,
      [CharacterEquipmentSlot.leftHand]: ShieldId.Buckler,
    },
  },
  [ClassEnum.Druid]: {
    proficiencies: {
      three: "staff",
      two: "spear",
      one: "bow",
    },
    startingSkills: [
      DruidSkillId.ThrowSpear,
      DruidSkillId.VineWhip,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.HideArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: SpearId.Javelin,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Monk]: {
    proficiencies: {
      three: "bareHand",
      two: "staff",
      one: "blade",
    },
    startingSkills: [
      MonkSkillId.FlurryOfBlows,
      MonkSkillId.PalmStrike,
      MonkSkillId.Meditation,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.Tunic,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: null,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Warlock]: {
    proficiencies: {
      three: "orb",
      two: "axe",
      one: "bow",
    },
    startingSkills: [
      WarlockSkillId.Corruption,
      WarlockSkillId.ChaosBolt,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: OrbId.Orb,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Duelist]: {
    proficiencies: {
      three: "sword",
      two: "shield",
      one: "bow",
    },
    startingSkills: [
      DuelistSkillId.DuelingStance,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: SwordId.ShortSword,
      [CharacterEquipmentSlot.leftHand]: ShieldId.Buckler,
    },
  },
  [ClassEnum.Witch]: {
    proficiencies: {
      three: "wand",
      two: "book",
      one: "dagger",
    },
    startingSkills: [
      WitchSkillId.PoisonDart as SkillId,
      WitchSkillId.ChaosBinding as SkillId,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: WandId.Wand,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Inquisitor]: {
    proficiencies: {
      three: "book",
      two: "bow",
      one: "wand",
    },
    startingSkills: [
      InquisitorSkillId.ExposeWeakness,
      InquisitorSkillId.RadiantSmite,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: BookWId.Bible,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Scholar]: {
    proficiencies: {
      three: "book",
      two: "sword",
      one: "dagger",
    },
    startingSkills: [
      ScholarSkillId.CognitiveOverload,
      ScholarSkillId.DisruptPattern,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.MageRobe,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: BookWId.Codex,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Engineer]: {
    proficiencies: {
      three: "bow",
      two: "hammer",
      one: "bareHand",
    },
    startingSkills: [
      EngineerSkillId.ExplosiveBolt,
      EngineerSkillId.BearTrap,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: BowId.ShortBow,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
  [ClassEnum.Nomad]: {
    proficiencies: {
      three: "blade",
      two: "bow",
      one: "dagger",
    },
    startingSkills: [
      NomadSkillId.TacticalSlash,
      NomadSkillId.AdaptiveStrike,
    ],
    startingEquipments: {
      [CharacterEquipmentSlot.headWear]: null,
      [CharacterEquipmentSlot.body]: BodyId.LeatherArmor,
      [CharacterEquipmentSlot.leg]: null,
      [CharacterEquipmentSlot.hand]: null,
      [CharacterEquipmentSlot.foot]: null,
      [CharacterEquipmentSlot.util]: null,
      [CharacterEquipmentSlot.ringL]: null,
      [CharacterEquipmentSlot.ringR]: null,
      [CharacterEquipmentSlot.earL]: null,
      [CharacterEquipmentSlot.earR]: null,
      [CharacterEquipmentSlot.neck]: null,
      [CharacterEquipmentSlot.rightHand]: BladeId.Scimitar,
      [CharacterEquipmentSlot.leftHand]: null,
    },
  },
};

export { classBonus };