export enum SkillId {
  Basic = "Basic,",
  ThrowPebble = "ThrowPebble",
  PanicSlash = "PanicSlash",
  Shriek = "Shriek",
  RetreatDash = "RetreatDash",
  Backstab = "Backstab",
  Bash = "Bash",
  Taunt = "Taunt",
  Cleave = "Cleave",
  HerosPose = "HerosPose",
  ShieldUp = "ShieldUp",
  FireBolt = "FireBolt",
  BurningHand = "BurningHand",
  FireBall = "FireBall",
  ArcaneShield = "ArcaneShield",
  Backdraft = "Backdraft",
  MendSpirit = "MendSpirit",
  HexOfRot = "HexOfRot",
  SpiritRattle = "SpiritRattle",
  ChaoticBlessing = "ChaoticBlessing",
}
