export enum BuffsAndDebuffsEnum {
  haste = "haste",
  slow = "slow",
  hiding = "hiding",
  taunt = "taunt",
  dazed = "dazed",
  fear = "fear",
  defenseUp = "defenseUp",
  burn = "burn",
  arcaneShield = "arcaneShield",
  retreat = "retreat",
  hexed = "hexed",
  spiritRattle = "spiritRattle",
  slaveDriver = "slaveDriver",
  cowardlyCharge = "cowardlyCharge",
}
