// Auto-generated file - do not edit manually
// Generated by: bun run scripts/extract-l10n.ts

import { BuffEnum, DebuffEnum } from './buffDebuffEnums';

export interface L10N {
  en: string;
  th: string;
}

export interface BuffDebuffTextObject {
  name: L10N;
  description: L10N;
  formula?: string;
}

export const buffsL10N: Record<BuffEnum, BuffDebuffTextObject> = {
  [BuffEnum.advancingPace]: {
    name: { en: "Advancing Pace", th: "ก้าวจังหวะรุก" },
    description: { en: "Always grants +2 Strength. Below skill level 5, reduces physical & magical defense by 1. At skill level 5+ (universalCounter = 1), removes the defense penalty and unlocks +35% AB speed. The skill level indicator is stored in universalCounter and remains constant throughout the buff's duration.", th: "ให้ +2 Strength เสมอ ต่ำกว่าระดับทักษะ 5 ลดพลังป้องกันกายภาพและเวทมนตร์ 1 ที่ระดับทักษะ 5+ (universalCounter = 1) ลบโทษป้องกันและปลดล็อก +35% AB speed ตัวบ่งชี้ระดับทักษะถูกเก็บใน universalCounter และคงที่ตลอดระยะเวลาของบัฟ" },
    formula: "STR +2; Below level 5: pDEF -1, mDEF -1; Level 5+: +35% AB speed (level indicator in universalCounter)",
  },
  [BuffEnum.aegisPulse]: {
    name: { en: "Aegis Pulse", th: "คลื่นป้องกันศักดิ์สิทธิ์" },
    description: { en: "Lingering Aegis shield pulsing after Aegis Shield is depleted by damage.", th: "คลื่นป้องกันศักดิ์สิทธิ์ที่คงอยู่หลังจากโล่ป้องกันศักดิ์สิทธิ์ถูกลดลงจากความเสียหาย" },
  },
  [BuffEnum.aegisShield]: {
    name: { en: "Aegis Shield", th: "โล่ป้องกันศักดิ์สิทธิ์" },
    description: { en: "A protective shield that absorbs damage. The shield value doesn't decrease automatically but is depleted when taking damage. When the shield is depleted by damage, Aegis Pulse is added.", th: "โล่ป้องกันที่ดูดซับความเสียหาย ค่าโล่ไม่ลดลงโดยอัตโนมัติแต่จะหมดลงเมื่อรับความเสียหาย เมื่อโล่หมดลงจากความเสียหาย Aegis Pulse จะถูกเพิ่ม" },
    formula: "Shield value depleted by damage (not by time); Aegis Pulse added when shield depleted",
  },
  [BuffEnum.arcaneShield]: {
    name: { en: "arcaneShield", th: "โล่เวทมนตร์" },
    description: { en: "A magical shield that protects the character. Each stack absorbs 1 point of damage.", th: "โล่เวทมนตร์ที่ปกป้องตัวละคร สแต็กที่มีอยู่จะดูดซับ 1 หน่วยของความเสียหาย" },
  },
  [BuffEnum.bless]: {
    name: { en: "bless", th: "อวยพร" },
    description: { en: "Gain <Advantage> on all saving rolls", th: "ได้ประโยชน์จากการทอยความสำเร็จการปกป้องทั้งหมด" },
  },
  [BuffEnum.cowardlyCharge]: {
    name: { en: "cowardlyCharge", th: "โจมตีแบบขี้ขลาด" },
    description: { en: "Increases <FORMULA>.", th: "เพิ่ม <FORMULA>" },
    formula: "pATK +2, mATK +2",
  },
  [BuffEnum.curseMarkActive]: {
    name: { en: "Curse Mark Active", th: "เครื่องหมายคำสาปใช้งาน" },
    description: { en: "Grants bonus damage against marked enemies. The Intelligence modifier for bonus damage is stored in universalCounter and remains constant throughout the buff's duration.", th: "ให้ความเสียหายเพิ่มต่อศัตรูที่ถูกทำเครื่องหมาย โมดิไฟเออร์ปัญญาสำหรับความเสียหายเพิ่มถูกเก็บใน universalCounter และคงที่ตลอดระยะเวลาของบัฟ" },
    formula: "Bonus damage = INT mod (stored in universalCounter, constant during buff duration)",
  },
  [BuffEnum.defenseUp]: {
    name: { en: "defenseUp", th: "เพิ่มพลังป้องกัน" },
    description: { en: "Increases <FORMULA>.", th: "เพิ่ม <FORMULA>" },
    formula: "pDEF +2, mDEF +2",
  },
  [BuffEnum.duelingStance]: {
    name: { en: "Dueling Stance", th: "ท่าดวล" },
    description: { en: "Gain <FORMULA>.", th: "ได้รับ <FORMULA>" },
    formula: "pHIT +2, mHIT +2, dodge +2, pCRT +<COUNTER>, mCRT +<COUNTER>",
  },
  [BuffEnum.edgeCharge]: {
    name: { en: "Edge Charge", th: "ประจุขอบ" },
    description: { en: "Edge Charge can stack to the maximum of 5. Consumed by skills like EdgeBurst.", th: "สแต็กได้สูงสุด 5 สแต็กไม่ลดลงโดยอัตโนมัติและถูกใช้โดยทักษะเช่น EdgeBurst" },
    formula: "Max stacks = 5",
  },
  [BuffEnum.exposeWeaknessActive]: {
    name: { en: "Expose Weakness Active", th: "เปิดเผยจุดอ่อนใช้งาน" },
    description: { en: "Grants <Formula> bonus hit chance against exposed enemies. ", th: "ให้โอกาสตีเพิ่มต่อศัตรูที่ถูกเปิดเผย <Formula> " },
    formula: "<COUNTER> / 2",
  },
  [BuffEnum.haste]: {
    name: { en: "haste", th: "เร่งความเร็ว" },
    description: { en: "Increases agility by the haste value. While the buff is active, Character's AB guage gain will be doubled.", th: "เพิ่มความคล่องแคล่วเท่ากับค่า haste ในขณะที่บัฟเปิดใช้งาน AB จะได้รับประโยชน์จากการทอยความสำเร็จการปกป้องทั้งหมด" },
  },
  [BuffEnum.hiding]: {
    name: { en: "hiding", th: "ซ่อนตัว" },
    description: { en: "The character is hidden, making them harder to detect.", th: "ตัวละครซ่อนตัว ทำให้ตรวจจับได้ยากขึ้น" },
  },
  [BuffEnum.innerVeil]: {
    name: { en: "Inner Veil", th: "ผ้าคลุมภายใน" },
    description: { en: "Increases dodge by 2", th: "เพิ่มหลบหลีก 2" },
  },
  [BuffEnum.parry]: {
    name: { en: "Parry", th: "ปัดป้อง" },
    description: { en: "When attacked by a non magical attack, roll DC13 CONsave, if passed, negate the attack and deal <Formula> damage back to the attacker. Remove once counter is used.", th: "เมื่อถูกโจมตีด้วยการโจมตีที่ไม่ใช่เวท ทอย save DC13 CON หากสำเร็จ จะยกเลิกการโจมตีและสร้างความเสียหาย <Formula> ต่อผู้โจมตี ลบออกเมื่อตอบโต้ถูกใช้" },
    formula: "<WeaponDamage> × <SkillLevelMultiplier>",
  },
  [BuffEnum.planarAbsorption]: {
    name: { en: "Planar Absorption", th: "ดูดซับพลัง" },
    description: { en: "Each stack can absorb 1 magical damage.", th: "สแต็กสามารถดูดซับ 1 หน่วยของความเสียหายเวทมนตร์" },
  },
  [BuffEnum.precognition]: {
    name: { en: "Precognition", th: "การคาดการณ์" },
    description: { en: "When attacked roll <FORMULA> if passed, the attack will miss. {<COUNTER===1>} With special effect, when the attack missed, you gain 1 order.{/}", th: "เมื่อถูกโจมตี ทอย <FORMULA> หากสำเร็จ การโจมตีจะล้มเหลว {<COUNTER===1>} มีผลพิเศษพิเศษ เมื่อการโจมตีล้มเหลว คุณจะได้รับ 1 ออเดอร์{/}" },
    formula: "<LUKsave> vs DC 10",
  },
  [BuffEnum.rage]: {
    name: { en: "Rage", th: "เดือดดาล" },
    description: { en: "Gain <FORMULA>.", th: "ได้รับ <FORMULA>" },
    formula: "<pATK +2, pDEF -2, mDEF -2>",
  },
  [BuffEnum.regen]: {
    name: { en: "Regeneration", th: "ฟื้นฟู" },
    description: { en: "Restores HP each turn. The heal amount is based on 1d4 + Willpower modifier + Vitality modifier. The Willpower modifier is stored in the universal counter and remains constant throughout the buff's duration.", th: "ฟื้นฟู HP ในแต่ละเทิร์น ปริมาณการรักษาขึ้นอยู่กับ 1d4 + โมดิไฟเออร์ความตั้งใจ + โมดิไฟเออร์ความแข็งแกร่ง โมดิไฟเออร์ความตั้งใจถูกเก็บใน universal counter และคงที่ตลอดระยะเวลาของบัฟ" },
    formula: "Heal per turn = 1d4 + WIL mod (from universalCounter) + VIT mod",
  },
  [BuffEnum.retreat]: {
    name: { en: "retreat", th: "ถอยก่อน" },
    description: { en: "Increases dodge by 3.", th: "เพิ่มหลบหลีก 3" },
  },
  [BuffEnum.reversalPalm]: {
    name: { en: "Reversal Palm", th: "ฝ่ามือพลิก" },
    description: { en: "Ready to counter attacks. The skill level is stored in universalCounter and remains constant throughout the buff's duration.", th: "พร้อมตอบโต้การโจมตี ระดับทักษะถูกเก็บใน universalCounter และคงที่ตลอดระยะเวลาของบัฟ" },
    formula: "Skill level stored in universalCounter (constant during buff duration)",
  },
  [BuffEnum.slaveDriver]: {
    name: { en: "slaveDriver", th: "ขับทาส" },
    description: { en: "Works You Maggots!", th: "ทำงาน ไอ้พวกหนอนแมลง!" },
  },
  [BuffEnum.spellParry]: {
    name: { en: "Spell Parry", th: "ปัดเวท" },
    description: { en: "Reduces the next spell damage by <FORMULA>. And given self an Edge Charge. \nIf the amount of damage is 0, given 2 Edge Charge.", th: "ลดความเสียหายเวทครั้งถัดไป <FORMULA> และให้ตัวเอง Edge Charge. \nหากความเสียหายเป็น 0, ให้ Edge Charge 2 หน่วย" },
    formula: "5 + <INTmod>",
  },
  [BuffEnum.spiritRattle]: {
    name: { en: "spiritRattle", th: "กระดิ่งวิญญาณ" },
    description: { en: "Heals the character each turn for <FORMULA>", th: "รักษาตัวละครในแต่ละเทิร์น <FORMULA>" },
    formula: "1d4 + <WILmod>",
  },
  [BuffEnum.taunt]: {
    name: { en: "taunt", th: "ยั่วยุ" },
    description: { en: "Increases physical defense by 2. When the buff expires, the defense bonus is removed.", th: "เพิ่มพลังป้องกันกายภาพ 2 เมื่อบัฟหมดอายุ โบนัสป้องกันจะถูกลบ" },
    formula: "pDEF +2 (removed when buff expires)",
  },
  [BuffEnum.warCry]: {
    name: { en: "War Cry", th: "เสียงร้องศึก" },
    description: { en: "Get <FORMULA>.", th: "เพิ่ม <FORMULA>" },
    formula: "+<COUNTER> agility, +<COUNTER> strength",
  },
};

export const debuffsL10N: Record<DebuffEnum, BuffDebuffTextObject> = {
  [DebuffEnum.analyze]: {
    name: { en: "disrupt pattern: cooldown", th: "disrupt pattern: cooldown" },
    description: { en: "Cooldown debuff for the Analyze skill. Prevents using the skill until the cooldown expires.", th: "ดีบัฟคูลดาวน์สำหรับทักษะ Analyze ป้องกันการใช้ทักษะจนกว่าคูลดาวน์จะหมดอายุ" },
  },
  [DebuffEnum.bearTrap]: {
    name: { en: "Bear Trap", th: "กับดักหมี" },
    description: { en: "Caught in a bear trap, taking, It Hurts!", th: "เป้าหมายติดกับดักหมี รับความเสียหายจากกับดัก" },
  },
  [DebuffEnum.bleed]: {
    name: { en: "Bleed", th: "เลือดไหล" },
    description: { en: "Taking <Formula> true damage each turn.", th: "รับความเสียหาย <Formula> จริงในแต่ละเทิร์น" },
    formula: "1d3",
  },
  [DebuffEnum.blind]: {
    name: { en: "Blind", th: "ตาบอด" },
    description: { en: "Lose <FORMULA>.", th: "สูญเสีย <FORMULA>" },
    formula: "-3 pHIT, -3 mHIT",
  },
  [DebuffEnum.burn]: {
    name: { en: "burn", th: "เผาไหม้" },
    description: { en: "Take fire damage equal to stack number each turn", th: "รับความเสียหายไฟเท่ากับจำนวนสแต็กแต่ละเทิร์น" },
  },
  [DebuffEnum.charmed]: {
    name: { en: "Charmed", th: "สะกดจิต" },
    description: { en: "When attacking, this character confuse on who's the enemy, need to roll <Formula> if fail, the target will be of opposite group from their intention.", th: "เมื่อโจมตี ตัวละครจะสับสนว่าใครเป็นศัตรู ต้องทอย <Formula> หากล้มเหลว เป้าหมายจะอยู่ในกลุ่มตรงข้ามกับความตั้งใจของตัวละคร" },
    formula: "<WilSave> vs DC 15",
  },
  [DebuffEnum.critDef]: {
    name: { en: "Reduced Critical Defense", th: "การป้องกันคริติคอลลดลง" },
    description: { en: "Reduces critical defense <COUNTER>", th: "ลดการป้องกันคริติคอล <COUNTER>" },
  },
  [DebuffEnum.cursed]: {
    name: { en: "cursed", th: "ถูกสาป" },
    description: { en: "A curse that affects the target. The curse value decreases by 1 each turn.", th: "คำสาปที่ส่งผลต่อเป้าหมาย ค่าคำสาปลดลง 1 ในแต่ละเทิร์น" },
  },
  [DebuffEnum.dazed]: {
    name: { en: "dazed", th: "สับสน" },
    description: { en: "Reduces physical and magical hit chance by 2. When the debuff expires, the penalties are removed.", th: "ลดโอกาสตีกายภาพและเวทมนตร์ 2 เมื่อดีบัฟหมดอายุ โทษจะถูกลบ" },
    formula: "pHIT -2, mHIT -2 (removed when debuff expires)",
  },
  [DebuffEnum.disruptPattern]: {
    name: { en: "disrupt pattern: cooldown", th: "disrupt pattern: cooldown" },
    description: { en: "Disrupt Pattern: cooldown", th: "Disrupt Pattern: cooldown" },
  },
  [DebuffEnum.entangled]: {
    name: { en: "Entangled", th: "พันกัน" },
    description: { en: "The target is entangled. Each turn, the target must roll <FORMULA> or skip their turn. On success, they break free.", th: "เป้าหมายถูกพันกัน ในแต่ละเทิร์นเป้าหมายต้องทอย DC 10 Strength save หรือข้ามเทิร์น หากสำเร็จจะหลุดพ้น" },
    formula: "DC10 <STRsave>",
  },
  [DebuffEnum.exposed]: {
    name: { en: "Exposed", th: "เปิดเผยจุดอ่อน" },
    description: { en: "The target takes additional <FORMULA> from all sources. {COUNTER>=1}[r]And CritDef -2[/r]{/}", th: "เป้าหมายรับความเสียหายเพิ่ม <FORMULA> จากทุกแหล่ง {COUNTER>=1}[r]และป้องกันคริติคอล -2[/r]{/}" },
    formula: "1d3 damage",
  },
  [DebuffEnum.fear]: {
    name: { en: "fear", th: "หวาดกลัว" },
    description: { en: "Reduces agility by the fear value. Each turn, the fear value decreases by 1 and agility is restored by 1.", th: "ลดความคล่องแคล่วตามค่า fear ในแต่ละเทิร์นค่า fear ลดลง 1 และความคล่องแคล่วฟื้นฟู 1" },
  },
  [DebuffEnum.healCooldown]: {
    name: { en: "heal: cooldown", th: "heal: cooldown" },
    description: { en: "Cooldown debuff for the Heal skill. Prevents using the skill until the cooldown expires.", th: "ดีบัฟคูลดาวน์สำหรับทักษะ Heal ป้องกันการใช้ทักษะจนกว่าคูลดาวน์จะหมดอายุ" },
  },
  [DebuffEnum.hexMark]: {
    name: { en: "Hex Mark", th: "เครื่องหมายสาป" },
    description: { en: "The target is marked with a hex sigil. The mark value decreases by 1 each turn.", th: "เป้าหมายถูกทำเครื่องหมายด้วยเครื่องหมายสาป ค่าเครื่องหมายลดลง 1 ในแต่ละเทิร์น" },
  },
  [DebuffEnum.hexed]: {
    name: { en: "hexed", th: "สาปเน่าเปื่อย" },
    description: { en: "Reduces endurance by 2. Each turn, the target takes <FORMULA>.", th: "ลดความอดทน 2 ในแต่ละเทิร์นเป้าหมายรับความเสียหาย <FORMULA>" },
    formula: "1d2 damage",
  },
  [DebuffEnum.massHealCooldown]: {
    name: { en: "mass heal: cooldown", th: "mass heal: cooldown" },
    description: { en: "Mass Heal: cooldown", th: "Mass Heal: cooldown" },
  },
  [DebuffEnum.mendSpiritCooldown]: {
    name: { en: "mend spirit: cooldown", th: "mend spirit: cooldown" },
    description: { en: "Cooldown debuff for the Mend Spirit skill. Prevents using the skill until the cooldown expires.", th: "ดีบัฟคูลดาวน์สำหรับทักษะ Mend Spirit ป้องกันการใช้ทักษะจนกว่าคูลดาวน์จะหมดอายุ" },
  },
  [DebuffEnum.slow]: {
    name: { en: "slow", th: "เชื่องช้า" },
    description: { en: "Reduces agility equal to stack number. While the debuff is active, Character's AB guage gain will be halved.", th: "ลดความคล่องแคล่วเท่ากับจำนวนสแต็ก ในขณะที่บัฟเปิดใช้งาน ความเร็วของ AB จะลดลงครึ่งหนึ่ง" },
  },
  [DebuffEnum.stun]: {
    name: { en: "Stun", th: "มึนงง" },
    description: { en: "Prevents the target from acting. Each turn, the target can attempt a save: d20 + Endurance modifier vs DC 10 + stun value. On success, the stun is removed.", th: "ป้องกันไม่ให้เป้าหมายทำการได้ ในแต่ละเทิร์นเป้าหมายสามารถพยายามเซฟ: d20 + โมดิไฟเออร์ความอดทน กับ DC 10 + ค่า stun หากสำเร็จ stun จะถูกลบ" },
    formula: "<EndSave> vs DC (10 + stun value)",
  },
};