// Auto-generated file - do not edit manually
// Generated by: bun run scripts/extract-l10n.ts

import {
  BasicSkillId,
  MobSkillId,
  ClericSkillId,
  SeerSkillId,
  ScholarSkillId,
  MageSkillId,
  MysticSkillId,
  RogueSkillId,
  SpellbladeSkillId,
  ShamanSkillId,
  BarbarianSkillId,
  WarriorSkillId,
  KnightSkillId,
  GuardianSkillId,
  PaladinSkillId,
  DruidSkillId,
  MonkSkillId,
  WarlockSkillId,
  DuelistSkillId,
  WitchSkillId,
  InquisitorSkillId,
  EngineerSkillId,
  NomadSkillId,
  type SkillId
} from './skillEnums';

export interface L10N {
  en: string;
  th: string;
}

export interface SkillTextObject {
  name: L10N;
  description: L10N;
  formula?: string;
}

export const skillsL10N: Record<SkillId, SkillTextObject> = {
  [BarbarianSkillId.Earthshatter]: {
    name: { en: "Earthshatter", th: "สั่นสะเทือนพิภพ" },
    description: { en: "Slam the ground with your weapon, sending a shock wave to the enemy line dealing damage all enemy in a line. \nDeals <FORMULA> blunt damage to each target. \nEach target [r]rolls DC8 ENDsave or becomes <DebuffDazed> for 1 turn.[/r]", th: "กระแทกพื้นด้วยอาวุธอย่างรุนแรง ส่งคลื่นสั่นสะเทือนใส่ศัตรูแถวหน้า \nสร้างความเสียหาย <FORMULA> ให้ศัตรูแถวหน้าทุกคน \nเป้าหมายแต่ละคนทอย [r]DC8 ENDsave ไม่ผ่านจะติด <DebuffDazed> 1 เทิร์น[/r]" },
    formula: "({5}'1d10':'1d8'{/} + <STRmod>) × <SkillLevelMultiplier>",
  },
  [BarbarianSkillId.Rage]: {
    name: { en: "Rage", th: "บ้าคลั่ง" },
    description: { en: "Roar fiercefully and enter the <BuffRage> state for {5}'4':'3'{/} turns.", th: "เข้าสู่สถานะ <BuffRage> เป็นเวลา {5}'4':'3'{/} เทิร์น" },
  },
  [BarbarianSkillId.RecklessSwing]: {
    name: { en: "Reckless Swing", th: "ฟาดไม่ยั้ง" },
    description: { en: "Swing your weapon recklessly attacking targeted enemy {5}'three':'two'{/} times, \neach dealing <FORMULA>. {5}\n :Hit roll suffer [r]-2[/r] penalty.{/}", th: "เหวี่ยงอาวุธฟาดไม่ยั้งใส่เป้าหมาย โจมตีต่อเนื่อง {5}'3':'2'{/} ครั้ง \nแต่ละครั้งสร้างความเสียหาย <FORMULA> ความแม่นยำในการโจมตีลดลง [r]2[/r]" },
    formula: "([r]0.7[/r] × <WeaponDamage> × <SkillLevelMultiplier>) × <MeleeRangePenalty>",
  },
  [BasicSkillId.Basic]: {
    name: { en: "Basic Attack", th: "โจมตีปกติ" },
    description: { en: "A basic attack, dealing damage equal to weapon's damage (+ modifier)", th: "การโจมตีปกติ สร้างความเสียหายเท่ากับความเสียหายจากอาวุธ (+ modifier)" },
    formula: "(Weapon damage + attribute modifier) × (1.0 + 0.1 per 2 character levels, max 1.5 at level 10)",
  },
  [ClericSkillId.Bless]: {
    name: { en: "Bless", th: "อวยพร" },
    description: { en: "Ask for the Blessing from Laoh, <BuffBlessing> all ally for 2 turns. \n{5}\nThe user [b]throw DC10 + <WILmod>, if success, gain +1 order.[/b]{/}", th: "อธิษฐานขอการอวยพรจากลาโอห์ เพื่อนร่วมทีมทั้งหมดได้รับสถานะ '<BuffBlessing>' 2 เทิร์น \n{5}\nหลังจากใช้ ทอย [b]DC10 + <WILmod>[/b] หากผ่านจะได้รับ +1 order{/}" },
  },
  [ClericSkillId.Heal]: {
    name: { en: "Heal", th: "รักษา" },
    description: { en: "Cast a healing spell, restore HP to an ally with least HP percentage. \nHeals for <FORMULA>. \n{3}\nThen [b]removes one random debuff[/b] from the target.{/}", th: "ร่ายเวทย์มนต์รักษา ฟื้นฟู HP ให้กับพันธมิตร \nรักษา <FORMULA> \n{3}\nจากนั้น[b]ลบหนึ่งดีบัฟแบบสุ่ม[/b]จากเป้าหมายด้วย{/}" },
    formula: "1d6 + <WILmod> + skill level",
  },
  [ClericSkillId.MassHeal]: {
    name: { en: "Mass Heal", th: "รักษาหมู่" },
    description: { en: "Cast a mass healing spell, restore all living allies. \nHeals for <FORMULA>. \n{4}\nThen [b]removes one random debuff[/b] from each healed ally.{/}", th: "ร่ายเวทย์มนต์รักษาหมู่ ฟื้นฟูเพื่อนร่วมทีมทุกคนที่ยังมีชีวิต \nรักษา <FORMULA> \n{4}\nจากนั้น[b]ลบหนึ่งดีบัฟแบบสุ่ม[/b]จากพันธมิตรที่ได้รับการรักษาแต่ละคน{/}" },
    formula: "1d6 + (<WILmod> + <CHAmod>) / 2 + skill level",
  },
  [ClericSkillId.Radiance]: {
    name: { en: "Radiance", th: "รัศมีศักดิ์สิทธิ์" },
    description: { en: "Unleash a flash of consecrated light dealing <FORMULA>. \nDeal additional [b]{5}'1d4 + 2':'1d4'{/}[/b] if the target is undead or fiend.", th: "ปล่อยแสงศักดิ์สิทธิ์ สร้างความเสียหาย <FORMULA> \nสร้างความเสียหายเพิ่มเติม [b]{5}'1d4 + 2':'1d4'{/}[/b] หากเป้าหมายเป็น undead หรือ fiend" },
    formula: "(1d6 + <WILmod>) × <SkillLevelMultiplier>",
  },
  [ClericSkillId.TurnUndead]: {
    name: { en: "Turn Undead", th: "ขับไล่ผี" },
    description: { en: "Cast a holy spell to destroy undead. \nDeal <FORMULA> true holy damage to non-undead targets. \nAgainst undead, target makes a [r](DC {5}'12':'10'{/}) WILsave roll[/r]. \nIf it failed to save, take 9999 true damage (instant kill). \nElse take [b]1d12 + <WILmod>[/b] holy damage.", th: "ร่ายเวทย์มนต์ศักดิ์สิทธิ์เพื่อทำลาย undead \nสร้างความเสียหายจริง <FORMULA> ต่อเป้าหมายที่ไม่ใช่ undead \nหากเป้าหมายเป็น undead เป้าหมายจะต้องทอย [r](DC {5}'12':'10'{/}) WILsave[/r] \nหากล้มเหลว สร้างความเสียหายจริง 9999 (ฆ่าทันที) \nหากสำเร็จ สร้างความเสียหายศักดิ์สิทธิ์ [b]1d12 + <WILmod>[/b]" },
    formula: "1d4 + <WILmod>",
  },
  [DruidSkillId.RejuvenatingMist]: {
    name: { en: "Rejuvenating Mist", th: "หมอกฟื้นฟู" },
    description: { en: "Release a gentle natural mist around the party. \nAll allies gain <BuffRegen> for {5}'3':'2'{/} turns: restore <FORMULA> HP at the start of their turn.", th: "ปล่อยหมอกธรรมชาติรอบทีม \nพันธมิตรทั้งหมดได้รับ <BuffRegen> {5}'3':'2'{/} เทิร์น: ฟื้นฟู <FORMULA> HP ที่เริ่มเทิร์น" },
    formula: "1d4 + <WILmod> {7} +2{/}",
  },
  [DruidSkillId.ThrowSpear]: {
    name: { en: "Throw Spear", th: "ขว้างหอก" },
    description: { en: "Throw your spear at the enemy. \nDealing <FORMULA> pierce damage multiplied by the range: \nfront-front {5}'1.0':'0.8'{/}\nfront-back {5}'1.4':'1.2'{/}\nback-back {5}'1.8':'1.6'{/}", th: "ขว้างหอกใส่ศัตรู \nความเสียหายขึ้นกับระยะ: front-front {5}'1.0':'0.8'{/}\nfront-back {5}'1.4':'1.2'{/}\nback-back {5}'1.8':'1.6'{/}" },
    formula: "([r]0.8[/r] × <WeaponDamage> + <SkillLevelMultiplier>)",
  },
  [DruidSkillId.VineWhip]: {
    name: { en: "Vine Whip", th: "เถาวัลย์" },
    description: { en: "Lashed a magical vine whip at an enemy.\nDeal <FORMULA> nature damage. \nTarget must [r]roll DC7 + <ControlMod> endurance save[/r] or get <DebuffEntangled> for 1 turn.", th: "ฟาดเป้าหมายด้วยเถาวัลย์เวทย์มนต์\nสร้างความเสียหายธรรมชาติ <FORMULA> \nเป้าหมายต้องทอย endurance save [r]DC7 + <ControlMod>[/r] หรือถูก <DebuffEntangled> 1 เทิร์น" },
    formula: "(1d6 + <WILmod>) × <SkillLevelMultiplier>",
  },
  [DuelistSkillId.BladeFlurry]: {
    name: { en: "Blade Flurry", th: "ชุดการโจมตีดาบ" },
    description: { en: "Unleash a rapid flurry of blade strikes. \nDeal {5}'3':'2'{/} hits of <FORMULA> slash damage. \nTargets can be the same or different.", th: "ปล่อยชุดการโจมตีดาบอย่างรวดเร็ว \nสร้างความเสียหาย {5}'3':'2'{/} ครั้ง แต่ละครั้ง <FORMULA> เป็นความเสียหายตัด \nเป้าหมายสามารถเป็นคนเดียวกันหรือต่างกัน" },
    formula: "([r]0.7[/r] × <WeaponDamage> × <SkillLevelMultiplier>) × <MeleeRangePenalty>",
  },
  [DuelistSkillId.DuelingStance]: {
    name: { en: "Dueling Stance", th: "ท่าดวล" },
    description: { en: "Adopt a focused dueling stance, enhancing your precision. \nGain <BuffDuelingStance> for {5}'3':'2'{/} turns. \n{5}\nGains [g]+2 crit[/g].{/}", th: "ใช้ท่าดวลที่มุ่งเน้น เพิ่มความแม่นยำ \nได้รับ <BuffDuelingStance> {5}'3':'2'{/} เทิร์น \n{5}\nได้รับ [g]+2 crit[/g]{/}" },
  },
  [DuelistSkillId.ParryRiposte]: {
    name: { en: "Parry & Riposte", th: "ปัดป้องและตอบโต้" },
    description: { en: "Assume a defensive stance, ready to parry and counter. \nGain <BuffParry> for {5}'2':'1'{/} turns. \nWhen attacked, [r]roll DC10 CONsave[/r]. If passed, negate the attack and deal <FORMULA> slash damage back to the attacker.", th: "ใช้ท่าป้องกัน พร้อมปัดป้องและตอบโต้ \nได้รับ <BuffParry> {5}'2':'1'{/} เทิร์น \nเมื่อถูกโจมตี ให้ทอย control save DC10 หากสำเร็จ จะยกเลิกการโจมตีและสร้างความเสียหาย <FORMULA> ต่อผู้โจมตี" },
    formula: "(1d6 + <DEXmod>) × <SkillLevelMultiplier>",
  },
  [DuelistSkillId.PreciseStrike]: {
    name: { en: "Precise Strike", th: "โจมตีแม่นยำ" },
    description: { en: "Execute a precise blade strike with perfect timing. \nDeals <FORMULA> slash damage. \n{5}\nGains [g]+2 crit[/g].{/}", th: "โจมตีด้วยดาบอย่างแม่นยำด้วยจังหวะที่สมบูรณ์แบบ \nสร้างความเสียหาย <FORMULA> เป็นความเสียหายตัด \n{5}\nได้รับ [g]+2 crit[/g]{/}" },
    formula: "((<WeaponDamage> × {5}'1.2':'1.0'{/}) × <SkillLevelMultiplier> × <MeleeRangePenalty>",
  },
  [EngineerSkillId.BearTrap]: {
    name: { en: "Bear Trap", th: "กับดักหมี" },
    description: { en: "Set a bear trap on the battlefield. The next time an enemy uses a melee (physical) attack, the trap triggers, dealing <FORMULA> pierce damage and removing the trap.", th: "วางกับดักหมีบนสนามรบ. ครั้งถัดไปที่ศัตรูใช้การโจมตีระยะประชิด (กายภาพ), กับดักจะทำงาน สร้างความเสียหายแทง <FORMULA> และลบกับดักออก" },
    formula: "(1d6 + <DEXmod>) × <SkillLevelMultiplier>",
  },
  [EngineerSkillId.ExplosiveBolt]: {
    name: { en: "Explosive Bolt", th: "ลูกธนูระเบิด" },
    description: { en: "Fire an explosive bolt that deals <FORMULA> fire damage to a target. If hit, deals 50% splash damage to adjacent enemies in the same row.", th: "ยิงลูกธนูระเบิดที่สร้างความเสียหายไฟ <FORMULA> แก่เป้าหมาย. หากโดน, สร้างความเสียหายสาด 50% แก่ศัตรูที่อยู่ติดกันในแถวเดียวกัน" },
    formula: "(1d8 + <DEXmod>) × <SkillLevelMultiplier>",
  },
  [GuardianSkillId.Bash]: {
    name: { en: "Bash", th: "ทุบสุดแรง" },
    description: { en: "Slam your weapon with overwhelming force, crushing your enemy's defenses.\nDeal <FORMULA> damage.\nTarget must [r]roll DC8 + STRmod ENDsave[/r] or become <DebuffStun> for 1 turn.", th: "ฟาดอาวุธด้วยแรงมหาศาล ทำลายการป้องกันของศัตรู\nสร้างความเสียหาย <FORMULA>\nเป้าหมายต้องทอย [r]DC8 + STRmod ENDsave[/r] หรือถูก <DebuffStun> 1 เทิร์น" },
    formula: "<WeaponDamage> × <MeleeRangePenalty>",
  },
  [GuardianSkillId.HerosPose]: {
    name: { en: "Hero's Pose", th: "ท่าเชิงฮีโร่" },
    description: { en: "Strike a heroic pose, channeling your inner strength.\nRoll DC{5}'10 - skill level':'15 - skill level'{/}. On success, restore <FORMULA> HP.\nThe higher your skill, the easier it becomes to inspire yourself.", th: "ใช้ท่าเชิงฮีโร่ ปลุกพลังภายใน\nทอย DC{5}'10 - เลเวลสกิล':'15 - เลเวลสกิล'{/} หากสำเร็จ ฟื้นฟู <FORMULA> HP\nยิ่งเลเวลสกิลสูง ยิ่งง่ายต่อการปลุกแรงใจ" },
    formula: "<VITmod> + skill level",
  },
  [GuardianSkillId.ShieldUp]: {
    name: { en: "Shield Up", th: "ยกโล่ขึ้น" },
    description: { en: "Raise your shield high, forming an impenetrable barrier.\nGain <BuffDefenseUp> for {5}'4':'3'{/} turns", th: "ยกโล่ขึ้นสูง สร้างกำแพงป้องกันที่แข็งแกร่ง\nได้รับ <BuffDefenseUp> เป็นเวลา {5}'4':'3'{/} เทิร์น" },
  },
  [GuardianSkillId.Taunt]: {
    name: { en: "Taunt", th: "ยั่วยุ" },
    description: { en: "Roar defiantly and draw all enemy attention to yourself.\nGain <BuffTaunt> for <FORMULA> turns", th: "คำรามท้าทายและดึงความสนใจของศัตรูทั้งหมดมาที่คุณ\nได้รับ <BuffTaunt> เป็นเวลา <FORMULA> เทิร์น" },
    formula: "2 + floor(0.5 × skill level) + floor(<CHAmod> / 2)",
  },
  [InquisitorSkillId.ExposeWeakness]: {
    name: { en: "Expose Weakness", th: "เปิดเผยจุดอ่อน" },
    description: { en: "Point out the enemy's sins and expose their vulnerabilities for all to see.\n{5}\nAlso reduces their [r]critical defense by 2[/r].{/}\n[b]You gain +floor(<WILmod> / 2) hit[/b] against exposed enemies.", th: "ชี้ให้เห็นบาปของศัตรูและเปิดเผยจุดอ่อนให้ทุกคนเห็น\n{5}\nยังลด [r]การป้องกันคริติคอล 2[/r] ด้วย{/}\n[b]คุณได้รับ +floor(<WILmod> / 2) hit[/b] ต่อเป้าหมายที่ถูกเปิดเผย" },
  },
  [InquisitorSkillId.JudgmentDay]: {
    name: { en: "Judgment Day", th: "วันพิพากษา" },
    description: { en: "Call down divine judgment upon your enemy, a pillar of pure radiance that burns away all impurity.\nDeal <FORMULA> holy damage.\n[r]Deal +50% damage[/r] if target has <DebuffExposed>.\n[r]Deal +1d8 bonus damage[/r] against undead or fiends.", th: "เรียกการพิพากษาจากสวรรค์ใส่ศัตรู เสาแสงศักดิ์สิทธิ์ที่เผาผลาญความไม่บริสุทธิ์ทั้งหมด\nสร้างความเสียหายศักดิ์สิทธิ์ <FORMULA>\n[r]สร้างความเสียหายเพิ่ม +50%[/r] หากเป้าหมายมี <DebuffExposed>\n[r]สร้างความเสียหายเพิ่ม +1d8[/r] ต่อ undead หรือ fiends" },
    formula: "{5}'2d8':'2d6'{/} + (<WILmod> + <PlanarMod>) × (1 + 0.15 × skill level)",
  },
  [InquisitorSkillId.PurgeMagic]: {
    name: { en: "Purge Magic", th: "ล้างเวทมนตร์" },
    description: { en: "Unleash purifying flames that strip away all magical enhancements, the stronger the magic, the greater the backlash.\nDeal <FORMULA> [r]true holy damage[/r] that bypasses all defenses.\nRemoves {5}'2':'1'{/} random buff(s) from the target.\n{5}\nDeals [r]+2 additional damage[/r].{/}", th: "ปล่อยเปลวไฟชำระล้างที่ลบการเสริมเวทมนตร์ทั้งหมด ยิ่งเวทมนตร์แข็งแกร่ง ยิ่งได้รับผลกระทบมากขึ้น\nสร้างความเสียหายศักดิ์สิทธิ์แท้ <FORMULA> [r]ที่ผ่านการป้องกันทั้งหมด[/r]\nลบบัฟแบบสุ่ม {5}'2':'1'{/} ตัวจากเป้าหมาย\n{5}\nสร้างความเสียหาย [r]เพิ่ม +2[/r]{/}" },
    formula: "1d4 + target's PlanarMod + number of target's buffs {5} + 2{/}",
  },
  [InquisitorSkillId.RadiantSmite]: {
    name: { en: "Radiant Smite", th: "การลงโทษด้วยแสง" },
    description: { en: "Channel divine wrath into a searing beam of light that smites the wicked.\nDeal <FORMULA> holy damage.\n[r]Deal +1d4 bonus damage[/r] against undead or fiends.\n[r]Deal +1d4 bonus damage[/r] against evil-aligned targets.", th: "รวมพลังพิพากษาจากสวรรค์เป็นลำแสงที่เผาผลาญผู้ชั่วร้าย\nสร้างความเสียหายศักดิ์สิทธิ์ <FORMULA>\n[r]สร้างความเสียหายเพิ่ม +1d4[/r] ต่อ undead หรือ fiends\n[r]สร้างความเสียหายเพิ่ม +1d4[/r] ต่อเป้าหมายที่มีความชั่วร้าย" },
    formula: "(1d6 + (<WILmod> + <PlanarMod>) / 2) × <SkillLevelMultiplier>",
  },
  [KnightSkillId.AdvancingPace]: {
    name: { en: "Advancing Pace", th: "ก้าวจังหวะรุก" },
    description: { en: "Channel planar force into disciplined footwork, moving with unstoppable momentum.\nGain <BuffAdvancingPace> for {5}4:3{/} turns.", th: "ถ่ายทอดพลังภายในสู่จังหวะก้าว เคลื่อนไหวด้วยโมเมนตัมที่ไม่อาจหยุดยั้ง\nได้รับ <BuffAdvancingPace> {5}4:3{/} เทิร์น" },
  },
  [KnightSkillId.PrecisionThrust]: {
    name: { en: "Precision Thrust", th: "แทงทะลุจุด" },
    description: { en: "Lunge at a front-line foe with surgical accuracy, finding the perfect opening.\nDeal <FORMULA> damage.with [b]+3 hit[/b].\n[b]Gains bonus crit[/b] if target has any debuff.", th: "พุ่งแทงศัตรูแถวหน้าอย่างแม่นยำ หาช่องว่างที่สมบูรณ์แบบ\nสร้างความเสียหาย <FORMULA> พร้อมกับ [b]+3 hit[/b]\n[b]ได้รับ crit เพิ่ม[/b] หากเป้าหมายมีดีบัฟ" },
    formula: "<WeaponDamage> × (1 + 0.1 × skill level) × <MeleeRangePenalty>",
  },
  [MageSkillId.ArcaneBolt]: {
    name: { en: "Arcane Bolt", th: "ลูกเวทมนตร์" },
    description: { en: "Unleash a focused bolt of raw arcane energy.\nDeal <FORMULA> arcane damage.", th: "ปล่อยลูกพลังงานเวทมนตร์ดิบ\nสร้างความเสียหายอาร์เคน <FORMULA>" },
    formula: "({5}'1d8':'1d6'{/} + <PlanarMod>) × <SkillLevelMultiplier>",
  },
  [MageSkillId.ArcaneShield]: {
    name: { en: "Arcane Shield", th: "โล่เวทมนตร์" },
    description: { en: "Weave a protective barrier of pure arcane energy that absorbs incoming harm.\nGain <FORMULA> stacks of <BuffArcaneShield>.", th: "ถักทอกำแพงป้องกันจากพลังงานอาร์เคนบริสุทธิ์ที่ดูดซับอันตราย\nได้รับ <FORMULA> สแตคของ <BuffArcaneShield>" },
    formula: "1d3 + floor(<PlanarMod> / 2) + floor(0.5 × skill level) {5}'+1d3'{/}",
  },
  [MageSkillId.Backdraft]: {
    name: { en: "Backdraft", th: "ไฟย้อนกลับ" },
    description: { en: "Ignite the flames already burning on your enemies, causing them to explode in a violent backdraft.\nTargets all enemies with <DebuffBurn>.\nDeal <FORMULA> fire damage per burn stack, then remove all burn stacks.\n[b]Heal yourself[/b] for total damage × (0.1 × skill level) {5} + 1d2 per stack: + 1 per stack{/}", th: "จุดไฟที่กำลังลุกไหม้บนศัตรู ทำให้ระเบิดเป็นไฟย้อนกลับอย่างรุนแรง\nโจมตีศัตรูทั้งหมดที่มี <DebuffBurn>\nสร้างความเสียหายไฟ <FORMULA> ต่อสแตคเผาไหม้ จากนั้นลบสแตคเผาไหม้ทั้งหมด\n[b]ฟื้นฟูตัวเอง[/b] ความเสียหายทั้งหมด × (0.1 × เลเวลสกิล) {5} + 1d2 ต่อสแตค: + 1 ต่อสแตค{/}" },
    formula: "total damage × (0.1 × skill level) {5}+ 1d2 per stack:+ 1 per stack{/}",
  },
  [MageSkillId.BurningHand]: {
    name: { en: "Burning Hand", th: "มือไฟแผดเผา" },
    description: { en: "Project waves of searing flame from your hand, engulfing all enemies in the front row.\nDeal <FORMULA> fire damage to each target.\nOn hit, target must [r]roll DC10 + <PlanarMod> ENDsave[/r] or get <DebuffBurn> {5}'2-3':'1-2'{/} stacks.\n{5}\nMay also strike one additional target from another row.{/}", th: "ปล่อยคลื่นเปลวไฟจากฝ่ามือ โอบล้อมศัตรูทั้งหมดในแถวหน้า\nสร้างความเสียหายไฟ <FORMULA> ต่อแต่ละเป้าหมาย\nเมื่อโดน เป้าหมายต้องทอย [r]ENDsave DC10 + <PlanarMod>[/r] หรือถูก <DebuffBurn> {5}'2-3':'1-2'{/} สแตค\n{5}\nอาจโจมตีเป้าหมายเพิ่มเติมอีกหนึ่งตัวจากแถวอื่น{/}" },
    formula: "({5}'1d8':'1d6'{/} + <PlanarMod>) x <SkillLevelMultiplier>",
  },
  [MageSkillId.FireBall]: {
    name: { en: "Fireball", th: "ลูกไฟระเบิด" },
    description: { en: "Unleash a blazing sphere of fire that explodes upon impact, engulfing 1–6 enemies in a devastating inferno.\nDeal <FORMULA> fire damage to each target.\nOn hit, target must [r]roll DC10 + <PlanarMod> ENDsave[/r] or get <DebuffBurn> 1–2 stacks.", th: "ปลดปล่อยลูกไฟทรงพลังที่ระเบิดกลางสนาม โอบล้อมศัตรู 1–6 ตัวในไฟนรกที่ทำลายล้าง\nสร้างความเสียหายไฟ <FORMULA> ต่อแต่ละเป้าหมาย\nเมื่อโดน เป้าหมายต้องทอย [r]ENDsave DC10 + <PlanarMod>[/r] หรือถูก <DebuffBurn> 1–2 สแตค" },
    formula: "{5}'1d12':'1d10'{/} + <PlanarMod> + 0.5 × skill level",
  },
  [MageSkillId.FireBolt]: {
    name: { en: "Fire Bolt", th: "ลูกไฟ" },
    description: { en: "Unleash a focused bolt of fire that streaks toward your enemy like a shooting star.\nDeal <FORMULA> fire damage.\nOn hit, target must [r]roll DC8 + <PlanarMod> ENDsave[/r] or get <DebuffBurn> 1–2 stacks.", th: "ปล่อยลูกไฟที่มุ่งเน้นพุ่งไปยังศัตรูเหมือนดาวตก\nสร้างความเสียหายไฟ <FORMULA>\nเมื่อโดน เป้าหมายต้องทอย [r]ENDsave DC8 + <PlanarMod>[/r] หรือถูก <DebuffBurn> 1–2 สแตค" },
    formula: "(1d6 + <PlanarMod>) × <SkillLevelMultiplier>",
  },
  [MobSkillId.CommanderScream]: {
    name: { en: "Commander Scream!", th: "คำสั่งกรีดร้อง!" },
    description: { en: "Target all allies, each rolls DC15 willpower; on fail gain Fear 2t and Cowardly Charge 2t: consume 2 chaos, 2 sp: produce 1 earth", th: "เลือกพันธมิตรทั้งหมด ทอย DC15 willpower ถ้าล้มเหลวได้ Fear 2 เทิร์น และ Cowardly Charge 2 เทิร์น: ใช้ 2 chaos, 2 sp: สร้าง 1 earth" },
  },
  [MobSkillId.PanicSlash]: {
    name: { en: "Panic Slash", th: "ฟันแบบตื่นตระหนก" },
    description: { en: "A reckless melee attack. Deals 1.0× physical damage (+skill Level) with a -4 hit roll penalty, but grants +2 crit roll instead.", th: "การโจมตีระยะประชิดแบบไม่คิดหน้าคิดหลัง สร้างความเสียหายกายภาพ 1.0× (+เลเวบของสกิล) โอกาสโจมตีโดนลดลง 4 แต่โอกาสเกิดคริติคอลเพิ่มขึ้น 2" },
  },
  [MobSkillId.Shriek]: {
    name: { en: "Shriek", th: "กรีดร้อง" },
    description: { en: "A panicked shriek all enemy must roll DC10 willpower save, if failed gain Minor Fear. the user also have roll D20, if the result is 15+ gain 1 turn of taunt.", th: "กรีดร้องด้วยความตื่นตระหนก ศัตรูทั้งหมดต้องทอย DC10 willpower save, ถ้าล้มเหลวจะทำให้เกิด Minor Fear ผู้ใช้ทอย D20, ถ้าผลลัพธ์คือ 15+ จะได้รับสถานะยั่วยุ 1 เทิร์น" },
  },
  [MobSkillId.ThrowPebble]: {
    name: { en: "Throw Pebble", th: "ขว้างก้อนหิน" },
    description: { en: "A simple ranged attack with a pebble. Deals 1d6 blunt damage. If hit, target must roll DC10 endurance saves or dazed.", th: "การโจมตีระยะไกลด้วยก้อนหิน สร้างความเสียหาย blunt 1d6 หน่วย หากโจมตีถูก เป้าหมายจะต้องทอย DC10 endurance saves หรือติดสถานะสับสน" },
  },
  [MobSkillId.Whip]: {
    name: { en: "Whip!", th: "แส้!" },
    description: { en: "Attack one enemy deal 1d6 damage + all (Slave Drive) stacks*2 * (1+(skillLevel*0.1)), after attack, remove slave driver stacks", th: "โจมตีศัตรูหนึ่งตัว สร้างความเสียหาย 1d6 + (สแต็ค Slave Driver ทั้งหมด)*2 * (1+(เลเวลสกิล*0.1)), หลังโจมตี ลบสแต็ค Slave Driver ทั้งหมด" },
  },
  [MobSkillId.WorksYouMaggots]: {
    name: { en: "Work You Maggots!", th: "ทำงานไอ้หนอน!" },
    description: { en: "Target one ally 'Goblin' deal 1d3 true damage and add a Buff: Slave Driver to self equal to damage dealt; target get abGauge += 5 + skill level: consume 2 sp : produce 1 chaos", th: "เลือกพันธมิตร 'ก๊อปลิน' หนึ่งตัว สร้างความเสียหายจริง 1d3 และเพิ่มบัฟ Slave Driver ให้ตัวเองเท่ากับความเสียหายที่ทำได้; เป้าหมายได้รับ abGauge += 5 + เลเวลสกิล: ใช้ 2 sp : สร้าง 1 chaos" },
  },
  [MonkSkillId.FlurryOfBlows]: {
    name: { en: "Flurry of Blows", th: "ชุดการโจมตี" },
    description: { en: "Unleash a rapid flurry of strikes, overwhelming your enemy with sheer speed.\nDeal {5}'3':'2'{/} hits of <FORMULA> blunt damage.\n[r]Damage reduced by 70%[/r] if wearing non-cloth armor.", th: "ปล่อยชุดการโจมตีอย่างรวดเร็ว ท่วมท้นศัตรูด้วยความเร็ว\nสร้างความเสียหายทื่อ {5}'3':'2'{/} ครั้ง แต่ละครั้ง <FORMULA>\n[r]ความเสียหายลดลง 70%[/r] หากสวมเกราะที่ไม่ใช่ผ้า" },
    formula: "Palm Strike damage (if learned), else 1d4 + max(<STRmod>, <DEXmod>) × <MeleeRangePenalty>",
  },
  [MonkSkillId.Meditation]: {
    name: { en: "Meditation", th: "สมาธิ" },
    description: { en: "Enter a meditative state, channeling inner peace to restore your depleted resources.\nRestore <FORMULA> to your lowest resource (HP, MP, or SP) as percentage of max.", th: "เข้าสู่สถานะสมาธิ ควบคุมความสงบภายในเพื่อฟื้นฟูทรัพยากรที่หมดลง\nฟื้นฟู <FORMULA> ให้กับทรัพยากรที่ต่ำที่สุด (HP, MP, หรือ SP) เป็นเปอร์เซ็นต์ของค่าสูงสุด" },
    formula: "(1d4 + skill level + floor(<ControlMod> / 2))% of max",
  },
  [MonkSkillId.PalmStrike]: {
    name: { en: "Palm Strike", th: "ตบฝ่ามือ" },
    description: { en: "Channel internal force through your palm, striking with precision that bypasses armor.\nDeal <FORMULA> blunt damage.\nIgnores armor equal to skill level.\n[r]Damage reduced by 70%[/r] if wearing non-cloth armor.", th: "ควบคุมพลังภายในผ่านฝ่ามือ โจมตีด้วยความแม่นยำที่ผ่านเกราะ\nสร้างความเสียหายทื่อ <FORMULA>\nเพิกเฉยต่อเกราะเท่ากับเลเวลสกิล\n[r]ความเสียหายลดลง 70%[/r] หากสวมเกราะที่ไม่ใช่ผ้า" },
    formula: "({5}'1d8':'1d6'{/} + max(<STRmod>, <DEXmod>)) × <MeleeRangePenalty>",
  },
  [MysticSkillId.InnerVeil]: {
    name: { en: "Inner Veil", th: "ผ้าคลุมภายใน" },
    description: { en: "Weave a protective veil of planar energy around a frontline ally, obscuring them from enemy sight.\\Give <BuffInnerVeil> for {5}'3':'2'{/} turns.", th: "ถักทอผ้าคลุมป้องกันจากพลังงานระนาบรอบพันธมิตรแถวหน้า ทำให้ศัตรูมองไม่เห็น\nได้รับ <BuffInnerVeil> เป็นเวลา {5}'3':'2'{/} เทิร์น" },
  },
  [MysticSkillId.MistStep]: {
    name: { en: "Mist Step", th: "ก้าวหมอก" },
    description: { en: "Shift like mist to a safer position, becoming one with the air itself.\nIf in front row: move to backline.\nIf in back row: gain <BuffRetreat> for {5}'2':'1'{/} turns.\nRemoves <DebuffSlow> if present.", th: "เคลื่อนไหวเหมือนหมอกไปยังตำแหน่งที่ปลอดภัยกว่า กลายเป็นหนึ่งเดียวกับอากาศ\nหากอยู่ในแถวหน้า: ย้ายไปแถวหลัง\nหากอยู่ในแถวหลัง: ได้รับ <BuffRetreat> เป็นเวลา {5}'2':'1'{/} เทิร์น\nลบ <DebuffSlow> หากมีอยู่" },
  },
  [MysticSkillId.PlanarAbsorption]: {
    name: { en: "Planar Absorption", th: "ดูดซับพลัง" },
    description: { en: "Channel planar energy into a protective barrier that absorbs magical harm.\nGain <FORMULA> stacks of <BuffPlanarAbsorption>.", th: "ควบคุมพลังงานแห่งระนาบเป็นกำแพงป้องกันที่ดูดซับอันตรายจากเวทมนตร์\nได้รับ <FORMULA> สแตคของ <BuffPlanarAbsorption>" },
    formula: "(2d3 + <INTmod> + floor(<ControlMod> / 2)) × <SkillLevelMultiplier>",
  },
  [MysticSkillId.ReversalPalm]: {
    name: { en: "Reversal Palm", th: "ฝ่ามือพลิก" },
    description: { en: "Assume a defensive stance that redirects incoming attacks back at your foe.\nGain <BuffReversalPalm> for 1 turn.\nWhen attacked, [r]roll WILsave[/r]. If passed, deal <FORMULA> blunt damage to attacker and negate the attack.", th: "ใช้ท่าป้องกันที่สะท้อนการโจมตีที่เข้ามากลับไปที่ศัตรู\nได้รับ <BuffReversalPalm> 1 เทิร์น\nเมื่อถูกโจมตี ทอย [r]WILsave[/r] หากสำเร็จ สร้างความเสียหายทื่อ <FORMULA> ต่อผู้โจมตีและยกเลิกการโจมตี" },
    formula: "(1d6 + <DEXmod>) × <SkillLevelMultiplier>",
  },
  [NomadSkillId.AdaptiveStrike]: {
    name: { en: "Adaptive Strike", th: "การโจมตีปรับตัว" },
    description: { en: "Strike while repositioning. Deal weapon damage and change position from front to back or back to front. This attack has -2 hit penalty but no range penalty.", th: "โจมตีพร้อมเปลี่ยนตำแหน่ง. สร้างความเสียหายจากอาวุธและเปลี่ยนตำแหน่งจากหน้าไปหลังหรือหลังไปหน้า. การโจมตีนี้มี -2 hit แต่ไม่มี range penalty" },
    formula: "(Weapon damage + attribute modifier) × (1.0 + 0.1 per 2 character levels, max 1.5 at level 10)",
  },
  [NomadSkillId.TacticalShot]: {
    name: { en: "Tactical Shot", th: "ยิงเชิงกลยุทธ์" },
    description: { en: "Adapt your shot to enemy position.\nEnemy in front row: Throw hot sand into enemy eyes, dealing 1d2 true damage. Enemy must roll DC10 (DC12 at level 5) AGI save or get blind for 1 turn.\nEnemy in back row: Launch a powerful shot, dealing <FORMULA> piercing damage. No range penalty.", th: "ปรับการยิงตามตำแหน่งศัตรู\nศัตรูในแถวหน้า: โยนทรายร้อนเข้าตาศัตรู สร้างความเสียหายจริง 1d2. ศัตรูต้องทอย DC10 (DC12 ที่ระดับ 5) AGI save หรือถูก blind 1 เทิร์น\nศัตรูในแถวหลัง: ยิงอย่างทรงพลัง สร้างความเสียหายแทง <FORMULA>. ไม่มี range penalty" },
    formula: "(Weapon damage + attribute modifier) × (<SkillLevelMultiplier> + 0.3)",
  },
  [NomadSkillId.TacticalSlash]: {
    name: { en: "Tactical Slash", th: "ฟันเชิงกลยุทธ์" },
    description: { en: "Adapt your attack to your position.\nFront row: Engulf your weapon with fire and attack, dealing <FORMULA> fire damage. Enemy must roll DC10 (DC12 at level 5) Endurance save or get burn for 1d3 turns.\nBack row: Gain <BuffRetreat> for 1 turn.", th: "ปรับการโจมตีตามตำแหน่งของคุณ\nแถวหน้า: อาบอาวุธด้วยไฟและโจมตี สร้างความเสียหายไฟ <FORMULA>. ศัตรูต้องทอย DC10 (DC12 ที่ระดับ 5) Endurance save หรือถูก burn 1d3 เทิร์น\nแถวหลัง: ได้รับ <BuffRetreat> 1 เทิร์น" },
    formula: "(Weapon damage + attribute modifier + 1d4) × <SkillLevelMultiplier>",
  },
  [PaladinSkillId.AegisPulse]: {
    name: { en: "Aegis Pulse", th: "คลื่นป้องกันศักดิ์สิทธิ์" },
    description: { en: "Release the stored holy energy in a devastating pulse that heals allies and smites enemies.\nHeal all allies for <FORMULA> HP.\nDeal <FORMULA> holy damage to all enemies.", th: "ปลดปล่อยพลังงานศักดิ์สิทธิ์ที่สะสมไว้เป็นคลื่นที่ทำลายล้าง รักษาพันธมิตรและลงโทษศัตรู\nรักษาพันธมิตรทั้งหมด <FORMULA> HP\nสร้างความเสียหายศักดิ์สิทธิ์ <FORMULA> ให้ศัตรูทั้งหมด" },
    formula: "(1d4 + <WILmod>) × <SkillLevelMultiplier>",
  },
  [PaladinSkillId.AegisShield]: {
    name: { en: "Aegis Shield", th: "โล่ป้องกันศักดิ์สิทธิ์" },
    description: { en: "Summon a divine barrier of pure holy energy that protects you from harm.\nActivate <BuffAegisShield> with {5}'4':'3'{/} stacks.", th: "เรียกกำแพงศักดิ์สิทธิ์จากพลังงานศักดิ์สิทธิ์บริสุทธิ์ที่ปกป้องคุณจากอันตราย\nเปิดใช้งาน <BuffAegisShield> {5}'4':'3'{/} สแตค" },
  },
  [PaladinSkillId.DivineStrike]: {
    name: { en: "Divine Strike", th: "โจมตีศักดิ์สิทธิ์" },
    description: { en: "Channel divine wrath through your weapon, striking with the fury of the righteous.\nDeal <FORMULA> holy damage.\n[r]Deal +{5}'1d10':'1d6'{/} bonus damage[/r] against undead or fiends.", th: "ควบคุมความโกรธศักดิ์สิทธิ์ผ่านอาวุธ โจมตีด้วยความโกรธของคนชอบธรรม\nสร้างความเสียหายศักดิ์สิทธิ์ <FORMULA>\n[r]สร้างความเสียหายเพิ่ม +{5}'1d10':'1d6'{/}[/r] ต่อ undead หรือ fiends" },
    formula: "((<WeaponDamageWithoutAtrMod> × 1.2) + ((<STRmod> + <WILmod>) / 2)) × <SkillLevelMultiplier> × <MeleeRangePenalty>",
  },
  [RogueSkillId.Backstab]: {
    name: { en: "Backstab", th: "แทงข้างหลัง" },
    description: { en: "While you're hiding, slip into your enemy's blind spot and drive your blade deep into their vulnerable back.\nDeal <FORMULA> pierce damage.\n[b]Gains +{5}'5':'4'{/} crit[/b] if target has <DebuffFear> or <DebuffDazed>.", th: "ในขณะที่ซ่อนตัว ข้ามเข้าไปที่จุดที่ศัตรูมองไม่เห็น และทะลุจุดอ่อนของศัตรูที่หลัง\nสร้างความเสียหายแทง <FORMULA>\n[b]ได้รับ +{5}'5':'4'{/} crit[/b] หากเป้าหมายมี <DebuffFear> หรือ <DebuffDazed>" },
    formula: "({5}'1.5':'1.3'{/} × <WeaponDamage>) × <SkillLevelMultiplier>",
  },
  [RogueSkillId.BleedingCut]: {
    name: { en: "Bleeding Cut", th: "ตัดเลือดไหล" },
    description: { en: "Slice your enemy with a precise cut that leaves them bleeding profusely.\nDeal <FORMULA> slash damage.\nTarget must [r]roll DC{5}'12':'10'{/} ENDsave[/r] or get <DebuffBleed> 1d3 stacks.", th: "ตัดศัตรูด้วยการตัดที่แม่นยำ ทำให้เลือดไหลไม่หยุด\nสร้างความเสียหายตัด <FORMULA>\nเป้าหมายต้องทอย [r]ENDsave DC{5}'12':'10'{/}[/r] หรือถูก <DebuffBleed> 1d3 สแตค" },
    formula: "<WeaponDamage> × <SkillLevelMultiplier> × <MeleeRangePenalty>",
  },
  [RogueSkillId.Hiding]: {
    name: { en: "Hiding", th: "ซ่อนตัว" },
    description: { en: "Melt into the shadows, becoming one with the darkness.\nRoll D20 + <DEXmod> against DC{5}'8':'10'{/} + highest enemy INTmod + {5}'3':'5'{/} if in front row.\nIf passed, gain <BuffHiding> for 2 turns.", th: "ละลายเข้ากับเงามืด กลายเป็นหนึ่งเดียวกับความมืด\nทอย D20 + <DEXmod> กับ DC{5}'8':'10'{/} + INTmod สูงสุดของศัตรู + {5}'3':'5'{/} หากอยู่ในแถวหน้า\nหากสำเร็จ ได้รับ <BuffHiding> 2 เทิร์น" },
  },
  [RogueSkillId.RetreatDash]: {
    name: { en: "Retreat Dash", th: "วิ่งหนี" },
    description: { en: "Make a desperate dash to safety, putting distance between you and danger.\nGain <BuffRetreat> for {5}'2':'1'{/} turn.\nAttempts to move to backline.", th: "วิ่งหนีอย่างสิ้นหวัง สร้างระยะห่างระหว่างคุณกับอันตราย\nได้รับ <BuffRetreat> {5}'3':'2'{/} เทิร์น\nพยายามย้ายไปแถวหลัง" },
  },
  [RogueSkillId.ThrowingKnives]: {
    name: { en: "Throwing Knives", th: "ขว้างมีด" },
    description: { en: "Hurl a flurry of knives with deadly precision, striking multiple foes.\nThrow {5}'3':'2'{/} daggers at random targets, each dealing <FORMULA> pierce damage.\nTargets can be the same or different.", th: "ขว้างมีดหลายเล่มด้วยความแม่นยำที่ร้ายแรง โจมตีศัตรูหลายคน\nขว้าง {5}'3':'2'{/} มีดกระทำศัตรูที่สุ่ม แต่ละคนสร้างความเสียหายแทง <FORMULA>\nเป้าหมายสามารถเป็นคนเดียวกันหรือต่างกัน" },
    formula: "(1d4 + <DEXmod>) × <SkillLevelMultiplier>",
  },
  [ScholarSkillId.Analyze]: {
    name: { en: "Analyze", th: "วิเคราะห์" },
    description: { en: "Study your enemy's movements and mark their most vulnerable points.\nMark target with <DebuffExposed> for 2 turns.\n{5}\nAlso reduces their [r]critical defense by <INTmod> but not exceed 3 or below 1[/r].{/}", th: "ศึกษาการเคลื่อนไหวของศัตรูและทำเครื่องหมายจุดอ่อนที่สุด\nทำเครื่องหมายเป้าหมายด้วย <DebuffExposed> 2 เทิร์น\n{5}\nยังลด [r]การป้องกันคริติคอล 2[/r] ด้วย{/}" },
  },
  [ScholarSkillId.CognitiveOverload]: {
    name: { en: "Cognitive Overload", th: "ความล้นเกินของความคิด" },
    description: { en: "Overwhelm your enemy's mind with an overwhelming surge of arcane knowledge.\nDeal <FORMULA> [r]true arcane damage[/r] that bypasses all defenses.\nRefreshes 1 random debuff on the target.\nIf target has ≥3 debuffs, main dice becomes {5}'1d8':'1d6'{/}.", th: "ท่วมท้นจิตใจของศัตรูด้วยคลื่นความรู้อาร์เคนที่ล้นเกิน\nสร้างความเสียหายอาร์เคนแท้ <FORMULA> [r]ที่ผ่านการป้องกันทั้งหมด[/r]\nรีเฟรชดีบัฟแบบสุ่ม 1 ตัวบนเป้าหมาย\nหากเป้าหมายมีดีบัฟ ≥3 ตัว ความเสียหายกลายเป็น {5}'1d8':'1d6'{/}." },
    formula: "{5}'1d6':'1d4'{/} + <INTmod> × <SkillLevelMultiplier>",
  },
  [ScholarSkillId.DisruptPattern]: {
    name: { en: "Disrupt Pattern", th: "ทำลายรูปแบบ" },
    description: { en: "Disrupt your enemy's combat rhythm by identifying and breaking their attack patterns.\nForce target to [r]roll DC{5}'12':'10'{/} WILsave[/r].\nIf failed: target becomes <DebuffDazed> for 1 turn.\nIf passed: [r]reduce target's next initiative by {5}'30':'20'{/}[/r].", th: "ทำลายจังหวะการต่อสู้ของศัตรูโดยระบุและทำลายรูปแบบการโจมตี\nบังคับเป้าหมายให้ทอย [r]WILsave DC{5}'12':'10'{/}[/r]\nหากล้มเหลว: เป้าหมายถูก <DebuffDazed> 1 เทิร์น\nหากสำเร็จ: [r]ลด initiative ครั้งถัดไปของเป้าหมาย {5}'30':'20'{/}[/r]" },
  },
  [SeerSkillId.PlanarEcho]: {
    name: { en: "Planar Echo", th: "การสะท้อนพลังระนาบ" },
    description: { en: "Echo the planar energy around, dealing <FORMULA> arcane damage to a target. If hit, the target must roll DC10 LUKsave or decrease AB gauge by 10.", th: "คาดการณ์อนาคต, ได้รับพระการันตี Precognition ของ 1 รอบ: การคาดการณ์: ศัตรูต� procon" },
    formula: "1d6 + <CHAmod> * (1 + 0.1 * skill level)",
  },
  [SeerSkillId.Precognition]: {
    name: { en: "Precognition", th: "คาดการณ์" },
    description: { en: "See the future, gain Precognition buff for 1 turn.{5} With special effect, when the attack missed, you gain 1 order.{7} when used, roll a d20 + <LUKmod> if passed, gain 1 more turn of Precognition buff", th: "คาดการณ์อนาคต, ได้รับพระการันตี Precognition ของ 1 รอบ: การคาดการณ์: ศัตรูต� procon" },
  },
  [SeerSkillId.ThreadSnip]: {
    name: { en: "Thread Snip", th: "ตัดลวดระนาบ" },
    description: { en: "Look into the planar thread and pulled it away from an enemy: Deal <FORMULA> to an enemy, roll D14 (-1 per skill level) dice. If passed, randomly steal 1 element from the enemy", th: "มองไปยังสายใยพลังพลานาบของศัตรู และตัดมันออก: สร้างความเสียหาย <FORMULA> ให้ศัตรู, ทอยลูกเต๋า D14 (-1 ต่อเลเวลสกิล). หากสำเร็จ, สุ่มคัดลอกธาตุหนึ่งจากศัตรู" },
    formula: "(1d4 + <CHAmod>) × <SkillLevelMultiplier>",
  },
  [ShamanSkillId.ChaoticBlessing]: {
    name: { en: "Chaotic Blessing", th: "พรแห่งความยุ่งเหยิง" },
    description: { en: "Channel the chaotic forces of the planes, unleashing unpredictable energy.\n50% chance to deal <FORMULA> chaos damage to all enemies, or heal all allies for <FORMULA> HP.\n{5}\nHealed allies [r]roll DC10 WILsave[/r], if passed, [b]gain +1 chaos[/b].\nDamaged enemies [r]roll DC10 WILsave[/r], if failed, [r]lose 1 random resource[/r].{/}", th: "ควบคุมพลังแห่งระนาบที่ยุ่งเหยิง ปลดปล่อยพลังงานที่คาดเดาไม่ได้\n50% โอกาสสร้างความเสียหาย chaos <FORMULA> ให้ศัตรูทั้งหมด หรือรักษาพันธมิตรทั้งหมด <FORMULA> HP\n{5}\nพันธมิตรที่ได้รับการรักษา: ทอย [r]WILsave DC10[/r] หากสำเร็จ [b]ได้รับ +1 chaos[/b]\nศัตรูที่ถูกโจมตี: ทอย [r]WILsave DC10[/r] หากล้มเหลว [r]สูญเสียทรัพยากรแบบสุ่ม 1 หน่วย[/r]{/}" },
    formula: "{5}'1d8':'1d6'{/} + ((<WILmod> + <PlanarMod>) / 2) × <SkillLevelMultiplier>",
  },
  [ShamanSkillId.HexOfRot]: {
    name: { en: "Hex of Rot", th: "คำสาปเน่าเปื่อย" },
    description: { en: "Channel chaos energy to cause visible decay and rot on your enemy.\nDeal <FORMULA> chaos damage.\nTarget must [r]roll DC10 + <ControlMod> WILsave[/r] or get <DebuffHexed> for 2 turns.", th: "ควบคุมพลังงาน chaos เพื่อทำให้เกิดการเน่าเปื่อยที่มองเห็นได้บนศัตรู\nสร้างความเสียหาย chaos <FORMULA>\nเป้าหมายต้องทอย [r]WILsave DC10 + <ControlMod>[/r] หรือถูก <DebuffHexed> เป็นเวลา 2 เทิร์น" },
    formula: "1d4 + <PlanarMod> + 0.5 × skill level",
  },
  [ShamanSkillId.HolyRattle]: {
    name: { en: "Holy Rattle", th: "กระดิ่งพระพรหม" },
    description: { en: "Channel order energy through resonance, creating visible healing waves that flow to your allies.\nGrants <FORMULA> random allies <BuffSpiritRattle> for {5}3:2{/} turns.\nCharacters with <BuffSpiritRattle> heal for 1d4 + <WILmod> at the start of their turn.", th: "ควบคุมพลังงาน order ผ่านการสั่นพ้อง สร้างคลื่นการรักษาที่มองเห็นได้ที่ไหลไปยังพันธมิตร\nให้ <FORMULA> พันธมิตรแบบสุ่ม <BuffSpiritRattle> เป็นเวลา {5}3:2{/} เทิร์น\nผู้ที่มี <BuffSpiritRattle> จะรักษาตัวเอง 1d4 + <WILmod> ที่เริ่มเทิร์น" },
    formula: "2-6 allies based on skill level",
  },
  [ShamanSkillId.MendSpirit]: {
    name: { en: "Mend Spirit", th: "ช่อมจิตวิญญาณ" },
    description: { en: "Mend an ally's wounds with unstable spiritual energy that flows unpredictably.\nHeal a random injured ally for <FORMULA> HP.\nRoll D20: if 11+, [r]heal is halved[/r] and target [b]gains +1 chaos[/b] instead of full healing.", th: "ช่อมแผลของพันธมิตรด้วยพลังงานจิตที่ไม่เสถียรที่ไหลอย่างคาดเดาไม่ได้\nรักษาพันธมิตรที่บาดเจ็บแบบสุ่ม <FORMULA> HP\nทอย D20: หาก 11+ [r]การรักษาลดลงครึ่งหนึ่ง[/r] และเป้าหมาย [b]ได้รับ +1 chaos[/b] แทนการรักษาเต็มจำนวน" },
    formula: "(1d4 + <WILmod>) × <SkillLevelMultiplier>",
  },
  [SpellbladeSkillId.EdgeBurst]: {
    name: { en: "Edge Burst", th: "ระเบิดขอบ" },
    description: { en: "Unleash all accumulated edge charges in a devastating burst of arcane energy.\nConsume ALL <BuffEdgeCharge> stacks (min 1).\nDeal <FORMULA> arcane damage.\nDamage increases with each edge charge consumed.", th: "ปลดปล่อย edge charge ที่สะสมไว้ทั้งหมดในระเบิดพลังงานอาร์เคนที่ทำลายล้าง\nใช้สแตค <BuffEdgeCharge> ทั้งหมด (อย่างน้อย 1)\nสร้างความเสียหายอาร์เคน <FORMULA>\nความเสียหายเพิ่มขึ้นตามจำนวน edge charge ที่ใช้" },
    formula: "(<WeaponDamage> or Planar Edge dice if no weapon) + <PlanarMod> + (1d2 per <BuffEdgeCharge> stack) × <SkillLevelMultiplier>",
  },
  [SpellbladeSkillId.PlanarEdge]: {
    name: { en: "Planar Edge", th: "ขอบแห่งระนาบ" },
    description: { en: "Channel planar energy into your weapon's edge, creating a blade of pure arcane power.\nDeal <FORMULA> arcane damage.\n[b]Gain 1 <BuffEdgeCharge>[/b] (max 5 stacks).\nThis skill Damage dice is based on weapon's physical damage dice or if you don't equip any weapon the damage dice will be (1d6, 1d6, 1d8, 1d8 or 2d4) based on skill level.", th: "ควบคุมพลังงานระนาบเข้าสู่ขอบอาวุธ สร้างใบมีดจากพลังอาร์เคนบริสุทธิ์\nสร้างความเสียหายอาร์เคน <FORMULA>\n[b]ได้รับ <BuffEdgeCharge> 1 สแตค[/b] (สูงสุด 5 สแตค)\nลูกเต๋าความเสียหายของสกิลนี้ขึ้นอยู่กับความเสียหายกายภาพของอาวุธที่ถือ แต่ถ้าหากไม่ได้ถืออาวุธอยู่ ลูกเต๋าความเสียหายจะเป็น (1d6, 1d6, 1d8, 1d8, 2d4) ขึ้นอยู่กับเลเวลของสกิล" },
    formula: "(Damage Dice + <PlanarMod> + <BuffEdgeCharge> stacks) × <SkillLevelMultiplier>",
  },
  [SpellbladeSkillId.SpellParry]: {
    name: { en: "Spell Parry", th: "ปัดเวท" },
    description: { en: "Weave a defensive barrier of planar energy that deflects incoming spells.\nGain <BuffSpellParry> for {5}2:1{/} turn.\nReduces next spell's damage by 5 + <INTmod>.\nIf attacked by a spell, [b]gain 1 <BuffEdgeCharge>[/b] (2 if 0 damage taken).\n{5}\n[b]Gain 1 <BuffEdgeCharge>[/b] when used.{/}", th: "ถักทอเกราะป้องกันจากพลังงานระนาบที่เบี่ยงเบนเวทมนตร์ที่เข้ามา\nได้รับ <BuffSpellParry> {5}2:1{/} เทิร์น\nลดความเสียหายเวทครั้งถัดไป 5 + <INTmod>\nหากถูกโจมตีด้วยเวท [b]ได้รับ <BuffEdgeCharge> 1 สแตค[/b] (2 สแตคหากไม่ได้รับความเสียหาย)\n{5}\n[b]ได้รับ <BuffEdgeCharge> 1 สแตค[/b] เมื่อใช้{/}" },
  },
  [SpellbladeSkillId.WindSlash]: {
    name: { en: "Wind Slash", th: "ฟันลม" },
    description: { en: "Slice through the air with a blade of wind-infused arcane energy.\nDeal <FORMULA> wind damage.\nTarget must [r]roll DC7 + <PlanarMod> ENDsave[/r] or get <DebuffBleed> for 1d2 turns.\n{5}\nIf <BuffEdgeCharge> stacks > 0, [r]deal +0.5 damage per stack[/r] (rounded down).{/}", th: "ฟันผ่านอากาศด้วยใบมีดพลังงานอาร์เคนที่ผสมลม\nสร้างความเสียหายลม <FORMULA>\nเป้าหมายต้องทอย [r]ENDsave DC7 + <PlanarMod>[/r] หรือถูก <DebuffBleed> 1d2 เทิร์น\n{5}\nหากสแตค <BuffEdgeCharge> > 0 [r]สร้างความเสียหายเพิ่ม +0.5 ต่อสแตค[/r] (ปัดลง){/}" },
    formula: "Planar Edge damage × <SkillLevelMultiplier>",
  },
  [WarlockSkillId.ChaosBolt]: {
    name: { en: "Chaos Bolt", th: "ลูกบอลวินาศ" },
    description: { en: "Hurl a bolt of pure chaotic energy that corrupts everything it touches.\nDeal <FORMULA> chaos damage.\nTarget must [r]roll DC8 + <PlanarMod> WILsave[/r] or get <DebuffHexed> for {5}'3':'2'{/} turns.", th: "ขว้างลูกบอลพลังงาน chaos บริสุทธิ์ที่ทำให้ทุกสิ่งที่สัมผัสเสื่อมสลาย\nสร้างความเสียหาย chaos <FORMULA>\nเป้าหมายต้องทอย [r]WILsave DC8 + <PlanarMod>[/r] หรือถูก <DebuffHexed> {5}'3':'2'{/} เทิร์น" },
    formula: "({5}'1d8':'1d6'{/} + <PlanarMod>) × <SkillLevelMultiplier>",
  },
  [WarlockSkillId.Corruption]: {
    name: { en: "Corruption", th: "การเสื่อมสลาย" },
    description: { en: "Channel dark energy to corrupt your enemy's very essence.\nDeal <FORMULA> dark damage immediately.\nTarget must [r]roll DC10 + <ControlMod> ENDsave[/r] or get <DebuffCursed> for 3 turns and <DebuffHexed> for 2 turns.\n{5}\nAlso applies [r]2 stacks of <DebuffBurn>[/r].{/}", th: "ควบคุมพลังงานมืดเพื่อทำให้แก่นแท้ของศัตรูเสื่อมสลาย\nสร้างความเสียหายมืด <FORMULA> ทันที\nเป้าหมายต้องทอย [r]ENDsave DC10 + <ControlMod>[/r] หรือถูก <DebuffCursed> 3 เทิร์น และ <DebuffHexed> 2 เทิร์น\n{5}\nยังเพิ่ม [r]<DebuffBurn> 2 สแตค[/r] ด้วย{/}" },
    formula: "1d4 + <PlanarMod>",
  },
  [WarlockSkillId.DarkPact]: {
    name: { en: "Darkness Overcharge", th: "วินาศกรรมมืด" },
    description: { en: "Sacrifice your own vitality to unleash overwhelming dark power.\nSacrifice {7}'8':'10'{/} HP to deal <FORMULA> [r]true dark damage[/r] that bypasses all defenses.", th: "เสียสละพลังชีวิตของตัวเองเพื่อปลดปล่อยพลังมืดที่ล้นเกิน\nเสียสละ {7}'8':'10'{/} HP เพื่อสร้างความเสียหายมืดแท้ <FORMULA> [r]ที่ผ่านการป้องกันทั้งหมด[/r]" },
    formula: "(2d10 + (2 × <PlanarMod>)) × (1 + 0.15 × skill level) {7}+'1d6' extra damage{/}",
  },
  [WarlockSkillId.LifeDrain]: {
    name: { en: "Life Drain", th: "ดูดชีวิต" },
    description: { en: "Drain the very life force from your enemy, converting their vitality into your own.\nDeal <FORMULA> erosion damage.\n[b]Heal yourself[/b] for {5}'75%':'50%'{/} + <VITmod>/10 of damage dealt.", th: "ดูดพลังชีวิตจากศัตรู แปลงพลังชีวิตของพวกเขาเป็นของคุณเอง\nสร้างความเสียหายกัดกร่อน <FORMULA>\n[b]ฟื้นฟูตัวเอง[/b] {5}'75%':'50%'{/} + <VITmod>/10 ของความเสียหายที่สร้าง" },
    formula: "{5}'1d10':'1d8'{/} + <PlanarMod> + <WILmod>",
  },
  [WarriorSkillId.Cleave]: {
    name: { en: "Cleave", th: "ฟันกวาด" },
    description: { en: "Swing your weapon in a wide arc, cutting through all enemies in the front row.\nDeal <FORMULA> damage to all enemies in the front row.", th: "ฟันอาวุธในวงกว้าง ตัดผ่านศัตรูทั้งหมดในแถวหน้า\nสร้างความเสียหาย <FORMULA> ให้ศัตรูทั้งหมดในแถวหน้า" },
    formula: "({5}'1.2':'1.0'{/} × <WeaponDamage>) × <SkillLevelMultiplier> × <MeleeRangePenalty>",
  },
  [WarriorSkillId.PowerStrike]: {
    name: { en: "Power Strike", th: "โจมตีแรง" },
    description: { en: "Channel all your strength into a single devastating strike.\nDeal <FORMULA> damage.", th: "ควบคุมพลังทั้งหมดของคุณเข้าสู่การโจมตีครั้งเดียวที่ทำลายล้าง\nสร้างความเสียหาย <FORMULA>" },
    formula: "({5}'1.5':'1.3'{/} × <WeaponDamage>) × <SkillLevelMultiplier> × <MeleeRangePenalty>",
  },
  [WarriorSkillId.WarCry]: {
    name: { en: "War Cry", th: "เสียงร้องศึก" },
    description: { en: "Let out a mighty battle cry that inspires you and your allies to fight harder.\nAffects yourself + <LEADmod> closest allies.\nGain <BuffWarCry> for {5}'3':'2'{/} turns.", th: "เปล่งเสียงร้องศึกที่ยิ่งใหญ่ที่ปลุกใจคุณและพันธมิตรให้ต่อสู้อย่างหนักขึ้น\nส่งผลต่อตัวเอง + <LEADmod> พันธมิตรที่ใกล้ที่สุด\nได้รับ <BuffWarCry> {5}'3':'2'{/} เทิร์น" },
  },
  [WitchSkillId.Bewitch]: {
    name: { en: "Bewitch", th: "สะกดจิต" },
    description: { en: "Weave a subtle charm that clouds your enemy's judgment and makes them see you as an ally.\nTarget must [r]roll DC10 + <ControlMod> WILsave[/r].\nIf failed, target gets <BuffCharm> for {5}'2':'1'{/} turn.", th: "ถักทอเสน่ห์ที่ทำให้จิตใจของศัตรูมืดมัวและทำให้พวกเขาเห็นคุณเป็นพันธมิตร\nเป้าหมายต้องทอย [r]WILsave DC10 + <ControlMod>[/r]\nหากล้มเหลว เป้าหมายได้รับ <BuffCharm> {5}'2':'1'{/} เทิร์น" },
  },
  [WitchSkillId.ChaosBinding]: {
    name: { en: "Chaos Binding", th: "ตุ๊กตาสาป" },
    description: { en: "Channel chaos energy into your enemy, creating a visible binding that causes ongoing corruption.\nDeal <FORMULA> dark damage immediately.\nTarget must [r]roll DC10 + <ControlMod> WILsave[/r] or get <DebuffHexed> for {5}'3':'2'{/} turns.\n{5}\nAlso applies <DebuffCursed> for 2 turns.{/}", th: "ควบคุมพลังงาน chaos เข้าสู่ศัตรู สร้างพันธะที่มองเห็นได้ที่ทำให้เกิดการเสื่อมสลายต่อเนื่อง\nสร้างความเสียหายมืด <FORMULA> ทันที\nเป้าหมายต้องทอย [r]WILsave DC10 + <ControlMod>[/r] หรือถูก <DebuffHexed> {5}'3':'2'{/} เทิร์น\n{5}\nยังเพิ่ม <DebuffCursed> 2 เทิร์นด้วย{/}" },
    formula: "(1d4 + <INTmod>) × <SkillLevelMultiplier>",
  },
  [WitchSkillId.ChaosBrand]: {
    name: { en: "Chaos Brand", th: "ประจุวินาที" },
    description: { en: "Brand your enemy with visible chaos energy that exposes their weaknesses for all to see.\nTarget gets <DebuffExposed> for {5}'3':'2'{/} turns.\nMarked enemies take [r]+1d3 damage from all sources[/r].\n{5}\nAlso reduces their [r]critical defense by 2[/r].{/}\n[b]You gain +floor(<INTmod> / 2) hit[/b] against marked enemies.", th: "ประทับตราพลังงาน chaos ที่มองเห็นได้บนศัตรู เปิดเผยจุดอ่อนของพวกเขาต่อทุกคน\nเป้าหมายได้รับ <DebuffExposed> {5}'3':'2'{/} เทิร์น\nศัตรูที่ถูกประทับตราจะรับ [r]ความเสียหายเพิ่ม +1d3 จากทุกแหล่ง[/r]\n{5}\nยังลด [r]การป้องกันคริติคอล 2[/r] ด้วย{/}\n[b]คุณได้รับ +floor(<INTmod> / 2) hit[/b] ต่อศัตรูที่ถูกประทับตรา" },
  },
  [WitchSkillId.PoisonDart]: {
    name: { en: "Poison Dart", th: "ลูกบอลคำสาป" },
    description: { en: "Launch a small magical dart tipped with potent poison that seeps through all defenses.\nDeal <FORMULA> [r]true poison damage[/r] that bypasses all defenses.\nTarget must [r]roll DC6 + <ControlMod> ENDsave[/r] or get <DebuffPoisoned> for {5}'3':'2'{/} turns.", th: "ขว้างลูกดอกเวทมนตร์เล็กๆ ที่มีปลายอาบยาพิษที่ซึมผ่านการป้องกันทั้งหมด\nสร้างความเสียหายพิษแท้ <FORMULA> [r]ที่ผ่านการป้องกันทั้งหมด[/r]\nเป้าหมายต้องทอย [r]ENDsave DC6 + <ControlMod>[/r] หรือถูก <DebuffPoisoned> {5}'3':'2'{/} เทิร์น" },
    formula: "({5}'1d4':'1d3'{/} + <INTmod>) × <SkillLevelMultiplier>",
  },
};